export const categories = [
  'Relevance',
  'Evidence & data',
  'Causation',
  'Language & framing',
  'Conversation tactics',
  'Decision traps',
] as const

export type Category = (typeof categories)[number]
export type Difficulty = 'Warm-up' | 'Deep dive' | 'Stretch'
export type PracticeMode = 'identify' | 'valid' | 'scenario' | 'speed'

export interface Fallacy {
  id: string
  name: string
  alsoKnownAs: string
  category: Category
  difficulty: Difficulty
  definition: string
  explanation: string
  simpleExample: string
  realisticExample: string
  whyItFails: string
  confusedWith: { id: string; distinction: string }[]
  tips: string[]
}

export interface Question {
  id: string
  mode: Exclude<PracticeMode, 'speed'>
  prompt: string
  correctFallacyId: string | null
  options: string[]
  explanation: string
  clue: string
  contrast: string
  difficulty: Difficulty
}

export const fallacies: Fallacy[] = [
  {
    id: 'strawman',
    name: 'Straw man',
    alsoKnownAs: 'Misrepresentation',
    category: 'Conversation tactics',
    difficulty: 'Warm-up',
    definition: 'Replacing someone’s actual position with a weaker version, then refuting that version.',
    explanation: 'A fair argument responds to what a person meant. A straw man quietly swaps in an easier target, so the speaker can feel as if they have won without engaging the original idea.',
    simpleExample: '“You want fewer meetings, so you want the team to stop communicating altogether.”',
    realisticExample: 'A city proposal suggests making two school streets car-free for 30 minutes at drop-off. A critic replies, “The people behind this want to ban cars from every road and shut down local businesses.”',
    whyItFails: 'The pilot is about a narrow time and place. Turning it into a total ban makes the proposal sound more extreme than it is, so the criticism lands on a position nobody proposed.',
    confusedWith: [
      { id: 'red-herring', distinction: 'A red herring changes the subject; a straw man changes the position being discussed.' },
      { id: 'false-dilemma', distinction: 'A false dilemma narrows the choices; a straw man distorts one side of the argument.' },
    ],
    tips: ['Restate the original claim in the strongest fair version.', 'Watch for “so you’re saying…” followed by an extreme paraphrase.', 'Compare the reply with the exact scope of the proposal.'],
  },
  {
    id: 'ad-hominem',
    name: 'Ad hominem',
    alsoKnownAs: 'Attack on the person',
    category: 'Conversation tactics',
    difficulty: 'Warm-up',
    definition: 'Attacking a speaker’s character, motives, or situation instead of addressing their claim.',
    explanation: 'A person can be rude, biased, or inconsistent and still make a true point. Personal information matters only when it bears directly on the evidence or reliability of the claim.',
    simpleExample: '“Ignore her recycling proposal; she is too messy to care about the planet.”',
    realisticExample: 'A tenant points out that the building’s fire exits are blocked. The landlord responds, “You are always complaining and you have never managed a property, so your safety concerns are nonsense.”',
    whyItFails: 'The tenant’s personality and experience do not answer whether the exits are blocked. The physical condition of the exits needs to be checked directly.',
    confusedWith: [
      { id: 'tu-quoque', distinction: 'Tu quoque is the special case where someone dismisses a claim by pointing to the speaker’s hypocrisy.' },
      { id: 'appeal-to-authority', distinction: 'Ad hominem attacks the source; an appeal to authority treats a source’s status as evidence.' },
    ],
    tips: ['Ask whether the personal detail changes the truth of the claim.', 'Separate “who said it” from “what evidence supports it.”', 'A relevant conflict of interest can be evidence about incentives, but it is not automatically a refutation.'],
  },
  {
    id: 'appeal-to-authority',
    name: 'Appeal to authority',
    alsoKnownAs: 'Argument from authority',
    category: 'Relevance',
    difficulty: 'Deep dive',
    definition: 'Treating an authority’s say-so as proof, especially outside their expertise or without checking the evidence.',
    explanation: 'Expert testimony can be useful evidence. The fallacy appears when a person’s reputation replaces the reasons for the conclusion, or when disagreement and uncertainty are presented as impossible.',
    simpleExample: '“A famous actor says this supplement works, so it definitely works.”',
    realisticExample: 'A popular chef says a city’s new rail project will bankrupt the region. A podcast host concludes, “She has built three restaurants, so there is no need to look at the transport budget.”',
    whyItFails: 'Restaurant experience does not establish expertise in public finance, and even a relevant economist can make a forecast that needs evidence. The status of the speaker is carrying the entire conclusion.',
    confusedWith: [
      { id: 'bandwagon', distinction: 'An appeal to authority leans on a person’s expertise or prestige; bandwagon leans on how many people agree.' },
      { id: 'anecdotal-evidence', distinction: 'Anecdotal evidence is a story used as data; authority is a source’s status used as support.' },
    ],
    tips: ['Check whether the authority is qualified in this exact domain.', 'Look for independent reasons beyond the title or celebrity.', '“Experts disagree” means the issue needs weighing, not automatic certainty.'],
  },
  {
    id: 'false-dilemma',
    name: 'False dilemma',
    alsoKnownAs: 'False dichotomy / Either-or',
    category: 'Language & framing',
    difficulty: 'Warm-up',
    definition: 'Presenting two options as the only choices when meaningful alternatives exist.',
    explanation: 'Some decisions really are binary, but many arguments use a forced choice to make a moderate, mixed, or unchosen option disappear.',
    simpleExample: '“Either you support this exact plan, or you do not care about the problem.”',
    realisticExample: 'During a budget meeting, the director says, “We can either cancel the youth program or approve the full 18% fee increase. There is no third option.”',
    whyItFails: 'The team could phase the increase, reduce another cost, seek a grant, or change the program’s scope. Declaring only two options makes urgency do the work of analysis.',
    confusedWith: [
      { id: 'strawman', distinction: 'A false dilemma removes options; a straw man exaggerates an opponent’s position.' },
      { id: 'slippery-slope', distinction: 'A false dilemma says there are only two paths; a slippery slope predicts a chain of consequences.' },
    ],
    tips: ['Ask “what other options are there?”', 'Notice all-or-nothing language: either, only, must choose.', 'Check if the choices are genuinely mutually exclusive.'],
  },
  {
    id: 'slippery-slope',
    name: 'Slippery slope',
    alsoKnownAs: 'Domino argument',
    category: 'Causation',
    difficulty: 'Deep dive',
    definition: 'Claiming that one step will inevitably trigger an extreme chain of events without enough support.',
    explanation: 'Consequences can be connected, but a slippery-slope argument skips the probability and safeguards at each link. The final disaster is used to condemn the first, much smaller step.',
    simpleExample: '“If we let students redo one quiz, soon nobody will meet deadlines and school will become meaningless.”',
    realisticExample: 'A library considers allowing food in one study room. A resident argues, “Once we allow sandwiches, the rooms will smell, pests will arrive, books will be ruined, and the library will have to close.”',
    whyItFails: 'The argument assumes every link is inevitable and ignores rules, cleaning, monitoring, and the possibility of stopping the policy. A possible chain is not a proven chain.',
    confusedWith: [
      { id: 'false-dilemma', distinction: 'A slippery slope is about an unsupported sequence; a false dilemma is about an incomplete menu of choices.' },
      { id: 'post-hoc', distinction: 'Post hoc says one event followed another; slippery slope predicts several future links.' },
    ],
    tips: ['Test each “then” separately.', 'Ask what evidence shows the next step is likely, not merely imaginable.', 'Look for a missing stopping point or safeguard.'],
  },
  {
    id: 'circular-reasoning',
    name: 'Circular reasoning',
    alsoKnownAs: 'Begging the question',
    category: 'Evidence & data',
    difficulty: 'Deep dive',
    definition: 'Using the conclusion as its own support instead of providing independent evidence.',
    explanation: 'The wording can sound like a reason while only restating the claim. If you accept the premise, you have already accepted the conclusion; nothing outside the loop has been added.',
    simpleExample: '“This rule is fair because it is a fair rule.”',
    realisticExample: 'A product review says, “Our privacy policy is trustworthy because the company only writes trustworthy privacy policies.”',
    whyItFails: 'The review never points to the policy’s data practices, audits, or limits. It assumes the exact quality it was supposed to establish.',
    confusedWith: [
      { id: 'no-true-scotsman', distinction: 'Circular reasoning loops back to the conclusion; no true Scotsman changes the definition to protect a generalization.' },
      { id: 'appeal-to-authority', distinction: 'An authority can be an external source; circular reasoning has no independent support at all.' },
    ],
    tips: ['Ask “what would someone who doubts this be shown?”', 'Rewrite the argument as premises and conclusion; check whether the conclusion appears as a premise.', 'A confident restatement is not new evidence.'],
  },
  {
    id: 'hasty-generalization',
    name: 'Hasty generalization',
    alsoKnownAs: 'Jumping to conclusions',
    category: 'Evidence & data',
    difficulty: 'Warm-up',
    definition: 'Drawing a broad conclusion from too few, unusual, or unrepresentative examples.',
    explanation: 'Generalizations need a sample that matches the population and a conclusion that respects uncertainty. A vivid encounter can be worth noticing without being enough to define a whole group.',
    simpleExample: '“Two buses were late today, so this bus company never runs on time.”',
    realisticExample: 'After two difficult onboarding calls, a manager says, “Freelancers are impossible to manage. They never communicate clearly.”',
    whyItFails: 'Two calls cannot represent every freelancer, and the manager may have noticed the frustrating cases more strongly than the ordinary ones.',
    confusedWith: [
      { id: 'anecdotal-evidence', distinction: 'An anecdote is a story used as support; hasty generalization is the overly broad leap from limited evidence.' },
      { id: 'cherry-picking', distinction: 'Hasty generalization may use too few cases; cherry-picking deliberately selects cases that favor a conclusion.' },
    ],
    tips: ['Count the examples and ask who is missing.', 'Check whether the sample was selected fairly.', 'Shrink the conclusion until it matches the evidence.'],
  },
  {
    id: 'cherry-picking',
    name: 'Cherry picking',
    alsoKnownAs: 'Selective evidence',
    category: 'Evidence & data',
    difficulty: 'Deep dive',
    definition: 'Selecting only the data or examples that support a claim while ignoring relevant counterevidence.',
    explanation: 'The problem is not simply having a small sample; it is treating a filtered slice as if it were the whole picture. The omitted evidence would materially change how strong the conclusion looks.',
    simpleExample: '“This diet worked for three friends, so the study showing mixed results is irrelevant.”',
    realisticExample: 'A software vendor shows its five fastest customer launches and says, “Our onboarding always takes less than a week,” while leaving out the 40% that needed a month.',
    whyItFails: 'The selected cases were chosen for their success. Without the full distribution, the claim hides the typical experience and exaggerates certainty.',
    confusedWith: [
      { id: 'survivorship-bias', distinction: 'Survivorship bias is a special selection error where failed or invisible cases disappear; cherry-picking can select any favorable slice.' },
      { id: 'hasty-generalization', distinction: 'Hasty generalization focuses on too little evidence; cherry-picking focuses on biased selection of evidence.' },
    ],
    tips: ['Ask how the examples were chosen.', 'Look for a denominator, baseline, or missing cases.', 'Compare the claim with the complete dataset, not the highlight reel.'],
  },
  {
    id: 'moving-goalposts',
    name: 'Moving the goalposts',
    alsoKnownAs: 'Shifting standards',
    category: 'Conversation tactics',
    difficulty: 'Deep dive',
    definition: 'Changing the standard of proof after it has been met so the claim can never be accepted.',
    explanation: 'Healthy skepticism states what evidence would change the mind. Moving the goalposts quietly raises or changes that requirement only after the other side delivers what was requested.',
    simpleExample: '“Show me one source.” “That source does not count; show me five.”',
    realisticExample: 'A manager asks a team to prove a new checkout flow reduces support tickets. After the team presents a controlled comparison, she says the result only counts if it also improves brand sentiment, revenue, and next year’s retention.',
    whyItFails: 'Those extra outcomes may be useful for a different decision, but they were not the agreed test. Treating them as retroactive requirements makes the original evidence impossible to satisfy.',
    confusedWith: [
      { id: 'burden-of-proof', distinction: 'Burden of proof asks who must support a claim; moving goalposts changes how much support counts after the fact.' },
      { id: 'no-true-scotsman', distinction: 'No true Scotsman changes a category’s definition; moving goalposts changes the evidence threshold.' },
    ],
    tips: ['State the acceptance criteria before evaluating the evidence.', 'Notice “yes, but…” followed by a new requirement.', 'Separate a new question from a refusal to accept the old answer.'],
  },
  {
    id: 'appeal-to-emotion',
    name: 'Appeal to emotion',
    alsoKnownAs: 'Emotional manipulation',
    category: 'Relevance',
    difficulty: 'Warm-up',
    definition: 'Using feelings as a substitute for evidence that would support the conclusion.',
    explanation: 'Emotion is part of human judgment and can highlight what matters. The fallacy appears when guilt, pity, pride, or outrage is treated as proof of what is true or what must be done.',
    simpleExample: '“If you really cared about your family, you would buy this insurance.”',
    realisticExample: 'A charity advert shows a heartbreaking story and says, “If you scroll past this page, you are choosing to let children suffer.”',
    whyItFails: 'The story may justify attention and compassion, but it does not by itself show that this charity is effective or that this donation is the best available action.',
    confusedWith: [
      { id: 'appeal-to-fear', distinction: 'Appeal to fear uses threat specifically; appeal to emotion is the broader category of replacing reasons with feelings.' },
      { id: 'red-herring', distinction: 'An emotional appeal can also distract, but its defining move is emotional pressure rather than topic change.' },
    ],
    tips: ['Name the feeling the argument is trying to create.', 'Ask what evidence would remain if the emotional story were removed.', 'Emotion can motivate a question without answering it.'],
  },
  {
    id: 'correlation-causation',
    name: 'Correlation ≠ causation',
    alsoKnownAs: 'False causal inference',
    category: 'Causation',
    difficulty: 'Deep dive',
    definition: 'Treating two things that vary together as proof that one causes the other.',
    explanation: 'A relationship can result from coincidence, reverse causation, a shared cause, or selection effects. Causal claims need a design or argument that rules out plausible alternatives.',
    simpleExample: '“People buy more umbrellas when it rains, so umbrellas cause bad weather.”',
    realisticExample: 'A company sees that employees who use a standing desk take fewer sick days and concludes the desks prevent illness, without checking job type, age, or the fact that healthier employees may choose them.',
    whyItFails: 'The variables move together, but the direction and mechanism are unclear. Healthier employees, different roles, or another workplace factor could explain the pattern.',
    confusedWith: [
      { id: 'post-hoc', distinction: 'Correlation can span a dataset; post hoc makes a causal leap specifically because one event came after another.' },
      { id: 'survivorship-bias', distinction: 'Correlation concerns a relationship between variables; survivorship bias concerns who is missing from the sample.' },
    ],
    tips: ['Ask whether there is a plausible mechanism.', 'Look for confounders and reverse causation.', 'Prefer “is associated with” until a causal comparison is justified.'],
  },
  {
    id: 'survivorship-bias',
    name: 'Survivorship bias',
    alsoKnownAs: 'Visible-winners bias',
    category: 'Evidence & data',
    difficulty: 'Stretch',
    definition: 'Studying visible successes while overlooking the failures or cases that disappeared from view.',
    explanation: 'The survivors are not a neutral sample. Their shared traits may be consequences of surviving rather than what caused survival, and the missing cases may contradict the lesson.',
    simpleExample: '“Successful founders all wake up at 5 a.m., so waking early creates success.”',
    realisticExample: 'A creator course interviews six influencers who quit their jobs before their channels took off. It never asks how many people quit, tried the same strategy, and ran out of savings without an audience.',
    whyItFails: 'The visible winners cannot show how common the outcome is among everyone who took the risk. The unseen failures are essential to estimate whether the strategy works.',
    confusedWith: [
      { id: 'cherry-picking', distinction: 'Survivorship bias is about missing failed cases; cherry-picking is any deliberate selection of favorable evidence.' },
      { id: 'hasty-generalization', distinction: 'Survivorship bias can produce a generalization, but the key error is the invisible denominator.' },
    ],
    tips: ['Ask “who tried this and did not make it?”', 'Look for a denominator of all attempts.', 'Separate traits shared by winners from traits that predict winning.'],
  },
  {
    id: 'burden-of-proof',
    name: 'Burden of proof',
    alsoKnownAs: 'Shifting the burden',
    category: 'Evidence & data',
    difficulty: 'Deep dive',
    definition: 'Demanding that others disprove a claim instead of providing support for the claim one has made.',
    explanation: 'The person making a substantive claim normally owes enough evidence for its strength and stakes. “You cannot prove me wrong” is not positive evidence that the claim is true.',
    simpleExample: '“Prove there is no invisible dragon in my garage.”',
    realisticExample: 'An influencer claims a supplement removes toxins from the body. When asked for studies, she says, “Skeptics have not proven that it does not work, so the claim stands.”',
    whyItFails: 'The absence of a disproof is not evidence of effectiveness. The person selling the claim controls the assertion and needs to show why anyone should believe it.',
    confusedWith: [
      { id: 'moving-goalposts', distinction: 'Burden of proof assigns who must support a claim; moving goalposts keeps changing what counts as sufficient support.' },
      { id: 'appeal-to-authority', distinction: 'An authority may be used as evidence; shifting the burden avoids giving evidence at all.' },
    ],
    tips: ['Track who made the positive claim.', 'Distinguish “not proven” from “false”; some claims remain unverified.', 'The burden can rise with the claim’s specificity and consequences.'],
  },
  {
    id: 'no-true-scotsman',
    name: 'No true Scotsman',
    alsoKnownAs: 'Purity test',
    category: 'Language & framing',
    difficulty: 'Stretch',
    definition: 'Protecting a generalization from counterexamples by redefining the group to exclude them.',
    explanation: 'Instead of revising a broad claim, the speaker adds an ad hoc condition for what a “real” member is. The new definition is created to save the claim, not because the category always had that boundary.',
    simpleExample: '“No real fan leaves early.” “Then those people were not real fans.”',
    realisticExample: 'A manager says, “People who care about quality never ship on Friday.” When a respected engineer does exactly that after a careful review, the manager replies, “Then she does not truly care about quality.”',
    whyItFails: 'The claim changed from a prediction about careful engineers to a definition that only counts people who behave as predicted. The counterexample is dismissed by wordplay.',
    confusedWith: [
      { id: 'circular-reasoning', distinction: 'No true Scotsman protects a category by changing membership; circular reasoning reuses the conclusion as support.' },
      { id: 'moving-goalposts', distinction: 'No true Scotsman shifts the definition of a person or group; moving goalposts shifts the evidence standard.' },
    ],
    tips: ['Ask whether the new criterion existed before the counterexample.', 'Watch for “real,” “true,” or “proper” used as a rescue word.', 'Check whether the category is being defined by the very conclusion at issue.'],
  },
  {
    id: 'tu-quoque',
    name: 'Tu quoque',
    alsoKnownAs: 'You too',
    category: 'Conversation tactics',
    difficulty: 'Warm-up',
    definition: 'Rejecting a claim by pointing out that the speaker is hypocritical or has done the same thing.',
    explanation: 'Hypocrisy may weaken trust in the messenger, but it does not make the claim false. The original issue remains unanswered.',
    simpleExample: '“You say I should save money, but you bought new shoes yesterday.”',
    realisticExample: 'A team lead asks everyone to stop sharing confidential screenshots. A colleague replies, “You shared one last year, so your privacy rule is invalid.”',
    whyItFails: 'The lead’s past behavior may deserve a separate conversation, but it does not change the risk created by sharing screenshots now.',
    confusedWith: [
      { id: 'ad-hominem', distinction: 'Tu quoque is a personal attack specifically about inconsistency; ad hominem includes broader attacks on character or circumstances.' },
      { id: 'red-herring', distinction: 'The hypocrisy is the distracting move in tu quoque; red herring can shift to any unrelated topic.' },
    ],
    tips: ['Answer the claim first, then discuss credibility separately.', 'Ask whether the speaker’s past action changes the truth of the advice.', '“You do it too” describes behavior, not a rebuttal.'],
  },
  {
    id: 'bandwagon',
    name: 'Bandwagon',
    alsoKnownAs: 'Appeal to popularity',
    category: 'Relevance',
    difficulty: 'Warm-up',
    definition: 'Treating widespread belief or behavior as proof that a claim is true, good, or safe.',
    explanation: 'Popularity can be useful evidence about taste or social behavior. It is not automatically evidence about accuracy, quality, or morality.',
    simpleExample: '“Everyone in the office uses this app, so it must protect our data.”',
    realisticExample: 'A broker says, “This neighborhood is the hottest one on the market—thousands of buyers want in—so purchasing this apartment is obviously a smart investment.”',
    whyItFails: 'Demand can affect price, but a crowd’s interest does not establish the apartment’s condition, affordability, or future return.',
    confusedWith: [
      { id: 'appeal-to-authority', distinction: 'Bandwagon counts supporters; appeal to authority relies on a particular person’s status or expertise.' },
      { id: 'anecdotal-evidence', distinction: 'An anecdote is one story; bandwagon appeals to the size or excitement of the crowd.' },
    ],
    tips: ['Replace “many people believe” with “what evidence do they have?”', 'Separate social proof from truth or quality.', 'Watch marketing language: best-selling, viral, everyone knows.'],
  },
  {
    id: 'sunk-cost',
    name: 'Sunk cost fallacy',
    alsoKnownAs: 'Throwing good money after bad',
    category: 'Decision traps',
    difficulty: 'Warm-up',
    definition: 'Continuing a failing choice because of resources already spent rather than future costs and benefits.',
    explanation: 'Past time, money, or effort cannot be recovered by itself. A rational decision asks what happens from now, while the fallacy treats the past as a debt that must be justified.',
    simpleExample: '“I paid for the movie, so I have to sit through it even though I feel ill.”',
    realisticExample: 'A team keeps funding an unreliable internal tool because it has already spent nine months building it. Nobody compares the remaining repair cost with switching to a simpler solution.',
    whyItFails: 'The nine months are gone either way. They matter for learning, but they are not a reason to spend another year if the future trade-off is worse.',
    confusedWith: [
      { id: 'appeal-to-emotion', distinction: 'Sunk cost often uses regret or pride emotionally, but the defining error is weighting unrecoverable past costs.' },
      { id: 'bandwagon', distinction: 'Bandwagon follows the crowd; sunk cost persists because of what one has already invested.' },
    ],
    tips: ['Imagine you had not started: would you choose this today?', 'Count only costs and benefits that can still change.', 'Treat past effort as information, not a bill the future must repay.'],
  },
  {
    id: 'red-herring',
    name: 'Red herring',
    alsoKnownAs: 'Distraction',
    category: 'Relevance',
    difficulty: 'Warm-up',
    definition: 'Introducing an irrelevant issue to pull attention away from the question being discussed.',
    explanation: 'A red herring can be true, interesting, or emotional. It is still a poor response if it does not bear on the original claim and only makes the conversation harder to follow.',
    simpleExample: '“Why was the report late?” “The team had a great lunch together.”',
    realisticExample: 'A customer asks why a delivery arrived damaged. The support reply describes the company’s sustainability mission and thanks the customer for supporting local jobs.',
    whyItFails: 'Those facts may be positive, but they do not explain the damage or what will be done. The reply changes the subject instead of resolving the complaint.',
    confusedWith: [
      { id: 'strawman', distinction: 'A red herring leaves the original claim behind; a straw man creates a distorted substitute for it.' },
      { id: 'appeal-to-emotion', distinction: 'A red herring can be emotional, but the essential move is irrelevance rather than emotional pressure.' },
    ],
    tips: ['Repeat the unanswered question out loud.', 'Ask “does this premise change the conclusion?”', 'Beware impressive context that never touches the disputed point.'],
  },
  {
    id: 'false-equivalence',
    name: 'False equivalence',
    alsoKnownAs: 'Moral equivalence',
    category: 'Language & framing',
    difficulty: 'Deep dive',
    definition: 'Treating two things as equivalent when their evidence, scale, intent, or consequences are meaningfully different.',
    explanation: 'Fair comparisons can reveal similarities, but false equivalence erases the differences that matter for the conclusion. “Both are imperfect” does not mean both are equally serious or equally supported.',
    simpleExample: '“Being five minutes late is basically the same as missing the entire event.”',
    realisticExample: 'A news discussion compares a single corrected typo in a report with a fabricated dataset and says, “Everyone makes mistakes, so neither issue should affect trust.”',
    whyItFails: 'Both involve error, but the scale, intent, and effect on reliability are not comparable. The shared label hides the relevant difference.',
    confusedWith: [
      { id: 'bandwagon', distinction: 'Bandwagon uses popularity; false equivalence uses a misleading comparison between two cases.' },
      { id: 'red-herring', distinction: 'False equivalence may be relevant but badly weighed; a red herring is irrelevant to the original question.' },
    ],
    tips: ['List the dimensions that matter before comparing.', 'Ask whether the shared feature is the decisive feature.', 'Do not confuse “both have flaws” with “both are equally flawed.”'],
  },
  {
    id: 'anecdotal-evidence',
    name: 'Anecdotal evidence',
    alsoKnownAs: 'One-story proof',
    category: 'Evidence & data',
    difficulty: 'Warm-up',
    definition: 'Using a personal story as if it were enough to establish a general fact or causal claim.',
    explanation: 'Stories are useful for generating hypotheses and understanding lived experience. They are weak proof for how common an outcome is because they lack comparison, sampling, and controls.',
    simpleExample: '“My neighbor never wears sunscreen and is fine, so sunscreen is unnecessary.”',
    realisticExample: 'A parent says a child’s concentration improved after removing a food and concludes the diet works for all children, despite having no baseline or comparison group.',
    whyItFails: 'The improvement could have other causes and the experience may not generalize. A story can deserve investigation without settling the question.',
    confusedWith: [
      { id: 'hasty-generalization', distinction: 'Anecdotal evidence is the type of support; hasty generalization is the broad conclusion drawn from too little support.' },
      { id: 'correlation-causation', distinction: 'Anecdotes often invite causal claims, but correlation/causation is about a relationship that may be measured across many cases.' },
    ],
    tips: ['Treat a story as a lead, not a verdict.', 'Ask what happened to comparable people who did not receive the intervention.', 'Look for base rates and repeated measurements.'],
  },
  {
    id: 'post-hoc',
    name: 'Post hoc',
    alsoKnownAs: 'After this, therefore because of this',
    category: 'Causation',
    difficulty: 'Deep dive',
    definition: 'Assuming that because one event happened after another, the first event caused the second.',
    explanation: 'Time order is necessary for many causes but never sufficient on its own. The later event may have been planned already, caused by a third factor, or simply coincidental.',
    simpleExample: '“I wore my lucky socks and then we won, so the socks caused the win.”',
    realisticExample: 'A café changes its playlist on Monday and sales rise that afternoon. The owner credits the music, ignoring a sunny holiday, a nearby festival, and a local promotion.',
    whyItFails: 'The change came first, but several other explanations fit the timing. Without a comparison or mechanism, sequence alone does not identify the cause.',
    confusedWith: [
      { id: 'correlation-causation', distinction: 'Post hoc is a time-order shortcut; correlation/causation can involve patterns without one event directly preceding another.' },
      { id: 'slippery-slope', distinction: 'Post hoc claims one past event caused a later one; slippery slope predicts an unsupported future chain.' },
    ],
    tips: ['Ask what else changed at the same time.', 'Check whether the outcome was already trending.', 'Use a comparison period or group where possible.'],
  },
  {
    id: 'equivocation',
    name: 'Equivocation',
    alsoKnownAs: 'Shifting meaning',
    category: 'Language & framing',
    difficulty: 'Stretch',
    definition: 'Using the same word in two different senses so an argument appears to connect when it does not.',
    explanation: 'The grammar stays smooth while the meaning slides. The conclusion may follow from one definition, but the premise relies on another.',
    simpleExample: '“A feather is light. What is light cannot be dark. So a feather cannot be dark.”',
    realisticExample: 'A manager says, “We need an agile team, and agile teams do not need plans. Therefore asking for a delivery plan is anti-agile.” The first “agile” means adaptable; the second is treated as unstructured.',
    whyItFails: 'Adaptability does not mean the absence of planning. The argument wins only by changing the meaning of “agile” midstream.',
    confusedWith: [
      { id: 'circular-reasoning', distinction: 'Equivocation changes a word’s meaning; circular reasoning keeps the meaning but loops the conclusion back as support.' },
      { id: 'false-dilemma', distinction: 'Equivocation blurs a term; a false dilemma hides available choices.' },
    ],
    tips: ['Circle repeated key words and define them each time.', 'Ask whether the conclusion uses the same sense as the premise.', 'Be especially careful with broad words such as freedom, natural, fair, or safe.'],
  },
  {
    id: 'composition',
    name: 'Composition fallacy',
    alsoKnownAs: 'Parts-to-whole error',
    category: 'Language & framing',
    difficulty: 'Stretch',
    definition: 'Assuming that what is true of each part must be true of the whole.',
    explanation: 'A group can have properties that none of its members have alone, and interactions can change the result. Individual excellence does not automatically add up to collective success.',
    simpleExample: '“Every ingredient is delicious, so this recipe cannot taste bad.”',
    realisticExample: 'A hiring panel chooses the strongest candidate in every department and concludes the company will automatically collaborate well, without considering incentives or communication between teams.',
    whyItFails: 'The conclusion concerns relationships across the company, not isolated talent. The properties of the parts do not guarantee the property of the system.',
    confusedWith: [
      { id: 'hasty-generalization', distinction: 'Composition moves from parts to a whole; hasty generalization moves from a sample to a wider population.' },
      { id: 'false-equivalence', distinction: 'Composition assumes properties transfer; false equivalence treats distinct cases as equally comparable.' },
    ],
    tips: ['Ask whether the conclusion concerns interactions or just components.', 'Look for missing system-level evidence.', 'Check whether the property is additive or relational.'],
  },
  {
    id: 'appeal-to-fear',
    name: 'Appeal to fear',
    alsoKnownAs: 'Scare tactic',
    category: 'Relevance',
    difficulty: 'Warm-up',
    definition: 'Using a threatening outcome as pressure instead of showing why the conclusion is supported.',
    explanation: 'Risk belongs in decisions, but a fear appeal exaggerates, presents uncertainty as certainty, or treats one frightening possibility as enough to settle the issue.',
    simpleExample: '“If you do not buy this alarm today, your family will be in danger tonight.”',
    realisticExample: 'A security vendor says, “If your school does not install our facial-recognition gates, the next incident will be your fault.” No incident data or comparison with other safeguards is offered.',
    whyItFails: 'The possibility of harm deserves a measured risk assessment. Fear is being used to force one purchase and assign blame without showing likelihood or effectiveness.',
    confusedWith: [
      { id: 'appeal-to-emotion', distinction: 'Appeal to fear is a specific emotional pressure tactic; appeal to emotion includes guilt, pity, pride, and other feelings.' },
      { id: 'slippery-slope', distinction: 'Fear can appear in a slippery slope, but a scare tactic does not need a multi-step chain.' },
    ],
    tips: ['Separate severity from likelihood.', 'Ask what evidence supports the promised protection.', 'Notice certainty words attached to hypothetical disasters.'],
  },
]

export const questions: Question[] = [
  {
    id: 'identify-01',
    mode: 'identify',
    prompt: 'The proposal asks the museum to close one weekday morning to reduce staffing costs. A critic says, “They want to make culture available only to rich people.”',
    correctFallacyId: 'strawman',
    options: ['strawman', 'false-dilemma', 'red-herring'],
    explanation: 'The proposal is narrowed to one morning, but the response turns it into a ban on access for an entire class of people. That distorted version is easier to attack than the actual cost proposal.',
    clue: 'The reply expands a limited scheduling change into a much more extreme motive and policy.',
    contrast: 'This is not a false dilemma because the speaker is not presenting two choices. It is not a red herring because the response still talks about the proposal, just inaccurately.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-02',
    mode: 'identify',
    prompt: '“Do not take Mira’s research on sleep seriously. She is disorganized and her desk is always a mess.”',
    correctFallacyId: 'ad-hominem',
    options: ['ad-hominem', 'appeal-to-authority', 'tu-quoque'],
    explanation: 'Messiness does not test the sleep research. The argument replaces an examination of methods or data with an attack on the researcher’s character.',
    clue: 'The reason given targets the person rather than the claim.',
    contrast: 'It is not tu quoque because there is no claim about hypocrisy or inconsistency. It is not an appeal to authority because no status is being used as evidence.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-03',
    mode: 'identify',
    prompt: 'A retired athlete says a city’s flood barrier is unnecessary. The host replies, “She won Olympic medals, so her engineering judgment settles the matter.”',
    correctFallacyId: 'appeal-to-authority',
    options: ['appeal-to-authority', 'bandwagon', 'anecdotal-evidence'],
    explanation: 'The athlete’s achievement does not establish expertise in flood engineering. Her status is being treated as conclusive instead of examining the barrier’s design and risk data.',
    clue: 'A person’s prestige is doing the work that domain-specific evidence should do.',
    contrast: 'This is not bandwagon because the evidence is one person’s status, not a crowd. It is not anecdotal evidence because no personal story is offered as data.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-04',
    mode: 'identify',
    prompt: '“Either we approve the full office renovation this quarter, or we accept that employee wellbeing does not matter.”',
    correctFallacyId: 'false-dilemma',
    options: ['false-dilemma', 'appeal-to-emotion', 'slippery-slope'],
    explanation: 'The sentence collapses a complex budget decision into approval or indifference. Phasing, reprioritizing, or choosing a smaller intervention disappear from view.',
    clue: 'Only two options are presented, and one is a moral accusation.',
    contrast: 'The emotional language adds pressure, but the core structure is the forced either-or. No chain of future consequences is predicted, so this is not a slippery slope.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-05',
    mode: 'identify',
    prompt: '“If we let customers return one sale item without a receipt, soon every purchase will be disputed, fraud will explode, and the store will close.”',
    correctFallacyId: 'slippery-slope',
    options: ['slippery-slope', 'false-dilemma', 'appeal-to-fear'],
    explanation: 'The argument leaps from a narrow exception to a chain of extreme outcomes without showing why each link is inevitable or why safeguards could not limit abuse.',
    clue: 'The concern is built from several unsupported “then” steps.',
    contrast: 'Fear is present, but the diagnostic feature is the predicted domino chain. A false dilemma would say there are only two choices, which this does not.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-06',
    mode: 'identify',
    prompt: '“The new process is reliable because it is a reliable process.”',
    correctFallacyId: 'circular-reasoning',
    options: ['circular-reasoning', 'appeal-to-authority', 'equivocation'],
    explanation: 'The sentence repeats the conclusion in slightly different words. It provides no test result, example, or independent reason to establish reliability.',
    clue: 'If you remove the conclusion, no evidence remains.',
    contrast: 'No authority is cited, so this is not an appeal to authority. The word “reliable” keeps one meaning, so it is not equivocation.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-07',
    mode: 'identify',
    prompt: 'After two tourists leave trash at the park, a council member says, “Visitors never respect public spaces.”',
    correctFallacyId: 'hasty-generalization',
    options: ['hasty-generalization', 'cherry-picking', 'survivorship-bias'],
    explanation: 'Two incidents are too little evidence to characterize every visitor. The conclusion is broader than the sample and ignores the many ordinary visits that may have gone unnoticed.',
    clue: 'The sample is tiny and the conclusion covers an entire population.',
    contrast: 'There is no clear deliberate selection of favorable cases, so cherry-picking is not the best label. The argument does not specifically focus on visible survivors either.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-08',
    mode: 'identify',
    prompt: 'A report highlights the three teams whose four-day workweek increased output and never mentions the teams whose output fell.',
    correctFallacyId: 'cherry-picking',
    options: ['cherry-picking', 'survivorship-bias', 'hasty-generalization'],
    explanation: 'The author deliberately presents only the favorable results. The omitted teams would change how strong the overall claim appears.',
    clue: 'The evidence is a selected highlight reel rather than the whole result set.',
    contrast: 'Survivorship bias is related, but there is no indication that the losing teams disappeared from view naturally; the report simply chooses not to show them.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-09',
    mode: 'identify',
    prompt: '“You asked me to show one study. I did. Now you say it must be a meta-analysis, and after that you will demand a ten-year trial.”',
    correctFallacyId: 'moving-goalposts',
    options: ['moving-goalposts', 'burden-of-proof', 'no-true-scotsman'],
    explanation: 'The requested standard changes after each answer, making acceptance impossible. A better discussion would state in advance what evidence would be enough for the claim.',
    clue: 'The requirement rises only after the previous requirement was met.',
    contrast: 'The burden of proof concerns who should support a claim; moving goalposts concerns changing what counts as support.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-10',
    mode: 'identify',
    prompt: '“If you loved your neighborhood, you would sign this petition today.”',
    correctFallacyId: 'appeal-to-emotion',
    options: ['appeal-to-emotion', 'appeal-to-fear', 'false-dilemma'],
    explanation: 'Love of the neighborhood is used to create guilt and urgency, but it does not show whether the petition’s proposed policy is effective or fair.',
    clue: 'The conclusion is pushed by a feeling rather than reasons about the petition.',
    contrast: 'No specific threat is made, so appeal to fear is too narrow. The speaker implies a moral test, but the main substitution is emotional pressure.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-11',
    mode: 'identify',
    prompt: 'People who use the new project-management app finish more projects. The team lead concludes the app is the sole reason they are more productive.',
    correctFallacyId: 'correlation-causation',
    options: ['correlation-causation', 'post-hoc', 'appeal-to-authority'],
    explanation: 'The groups differ in output, but the evidence does not isolate the app. Motivated teams may be more likely to adopt it, or other differences may explain the result.',
    clue: 'Two variables move together, but alternative causes are not ruled out.',
    contrast: 'There is no simple before-and-after story, so post hoc is less precise. No expert’s status is involved.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-12',
    mode: 'identify',
    prompt: 'A podcast interviews five entrepreneurs who became successful after dropping out. “School is clearly unnecessary for ambitious people,” the host concludes.',
    correctFallacyId: 'survivorship-bias',
    options: ['survivorship-bias', 'cherry-picking', 'hasty-generalization'],
    explanation: 'The visible successes are included while the many dropouts who did not become successful are absent. Without those attempts, the lesson confuses survival with a reliable recipe.',
    clue: 'The story only contains people who made it through the filter.',
    contrast: 'Cherry-picking is nearby, but the distinctive missing group is the unsuccessful dropouts. That invisible denominator is the key.',
    difficulty: 'Stretch',
  },
  {
    id: 'identify-13',
    mode: 'identify',
    prompt: '“You cannot prove that this crystal does not improve focus, so you have no basis to question my claim that it works.”',
    correctFallacyId: 'burden-of-proof',
    options: ['burden-of-proof', 'appeal-to-authority', 'circular-reasoning'],
    explanation: 'The person making the positive claim avoids providing evidence and treats the absence of disproof as support. Unverified is not the same as established.',
    clue: 'The claimant asks skeptics to do all the proving.',
    contrast: 'No authority is cited, and the conclusion is not repeated as its own reason. The problem is who is being asked to carry the burden.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-14',
    mode: 'identify',
    prompt: '“No serious designer misses a deadline.” When a respected designer does, her manager says, “Then she was never serious.”',
    correctFallacyId: 'no-true-scotsman',
    options: ['no-true-scotsman', 'moving-goalposts', 'circular-reasoning'],
    explanation: 'The manager protects the original generalization by redefining “serious designer” to exclude the counterexample. The new condition appears only because the claim was challenged.',
    clue: 'A counterexample is removed by changing who counts as a member of the group.',
    contrast: 'No evidence standard is being changed, so this is not moving the goalposts. The loop is about category membership, not a repeated conclusion.',
    difficulty: 'Stretch',
  },
  {
    id: 'identify-15',
    mode: 'identify',
    prompt: 'A colleague says everyone should lock their laptop before leaving. “You forgot once last year, so that advice is worthless,” replies the teammate.',
    correctFallacyId: 'tu-quoque',
    options: ['tu-quoque', 'ad-hominem', 'red-herring'],
    explanation: 'The teammate points to hypocrisy instead of considering whether locking laptops protects data. Past inconsistency does not make the safety advice false.',
    clue: 'The rebuttal is essentially “you did it too.”',
    contrast: 'Tu quoque is a specific ad hominem pattern about inconsistency. It is not a red herring because the personal history is the attempted rebuttal.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-16',
    mode: 'identify',
    prompt: '“This is the most downloaded budgeting app, so its forecasts must be accurate.”',
    correctFallacyId: 'bandwagon',
    options: ['bandwagon', 'appeal-to-authority', 'anecdotal-evidence'],
    explanation: 'Downloads show popularity, not forecasting accuracy. The crowd’s behavior is being treated as a quality test it cannot provide.',
    clue: 'The number of users is offered as evidence of truth or quality.',
    contrast: 'No individual expert is cited, and no personal story is used. Popularity is the source of the support.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-17',
    mode: 'identify',
    prompt: '“We have spent so much on this broken prototype that we have to keep funding it.”',
    correctFallacyId: 'sunk-cost',
    options: ['sunk-cost', 'appeal-to-emotion', 'bandwagon'],
    explanation: 'The money already spent cannot be recovered by spending more. The decision should compare the future cost of repair with the future value of alternatives.',
    clue: 'Past investment is treated as a reason to continue, regardless of what happens next.',
    contrast: 'Regret may make the decision emotional, but the logical error is counting an unrecoverable cost as if it were a future benefit.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-18',
    mode: 'identify',
    prompt: 'A customer asks why a refund is late. The company replies with a paragraph about its award-winning workplace culture.',
    correctFallacyId: 'red-herring',
    options: ['red-herring', 'appeal-to-emotion', 'strawman'],
    explanation: 'The workplace culture may be true, but it does not answer the refund question. The response distracts from the unresolved issue.',
    clue: 'The reply supplies impressive information that is irrelevant to the complaint.',
    contrast: 'It does not distort the customer’s position, so it is not a straw man. The main failure is topic relevance, not emotional pressure.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-19',
    mode: 'identify',
    prompt: '“The report has one corrected typo and the competitor fabricated a number. Both made errors, so neither can be trusted.”',
    correctFallacyId: 'false-equivalence',
    options: ['false-equivalence', 'red-herring', 'hasty-generalization'],
    explanation: 'The shared word “error” hides a major difference in scale and implications for trust. The cases are not equivalent just because both are imperfect.',
    clue: 'A superficial similarity erases a difference that matters to the conclusion.',
    contrast: 'Both examples are relevant to reliability, so this is not a red herring. The problem is the weight assigned to each case.',
    difficulty: 'Deep dive',
  },
  {
    id: 'identify-20',
    mode: 'identify',
    prompt: '“My cousin took this course and got promoted, so the course guarantees career growth.”',
    correctFallacyId: 'anecdotal-evidence',
    options: ['anecdotal-evidence', 'hasty-generalization', 'appeal-to-authority'],
    explanation: 'One success story cannot establish a guarantee. It does not show how many students took the course, what else they did, or how often the outcome occurs.',
    clue: 'A single vivid story is doing the job of broader evidence.',
    contrast: 'The overbroad conclusion is a consequence, but the clearest label focuses on the one-person story used as proof.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-21',
    mode: 'identify',
    prompt: '“I changed the office wallpaper on Tuesday and productivity went up on Wednesday, so the wallpaper fixed our focus problem.”',
    correctFallacyId: 'post-hoc',
    options: ['post-hoc', 'correlation-causation', 'slippery-slope'],
    explanation: 'The wallpaper came first, but sequence alone does not establish cause. Other changes or ordinary variation could explain the next day’s result.',
    clue: 'One event is credited solely because it happened before another.',
    contrast: 'This is a single before-and-after story, making post hoc more precise than a general correlation claim. No future chain is predicted.',
    difficulty: 'Warm-up',
  },
  {
    id: 'identify-22',
    mode: 'identify',
    prompt: '“Our team needs to be flexible. Flexible teams have no fixed process. Therefore documenting a process would make us inflexible.”',
    correctFallacyId: 'equivocation',
    options: ['equivocation', 'false-dilemma', 'circular-reasoning'],
    explanation: '“Flexible” shifts from adaptable to having no structure. The conclusion only follows after the key word silently changes meaning.',
    clue: 'The same word is doing two different jobs in the premises.',
    contrast: 'The options are not being limited to two, and the conclusion is not used as its own evidence. The problem is the sliding definition.',
    difficulty: 'Stretch',
  },
  {
    id: 'identify-23',
    mode: 'identify',
    prompt: 'Every engineer on the project is excellent, so the project team will definitely communicate well.',
    correctFallacyId: 'composition',
    options: ['composition', 'hasty-generalization', 'false-equivalence'],
    explanation: 'Individual skill does not guarantee a team-level property like communication. Coordination and incentives are properties of the group’s interactions.',
    clue: 'A property of each component is assumed to transfer automatically to the whole.',
    contrast: 'This is not a sample-to-population leap. It specifically moves from individual parts to a system-level conclusion.',
    difficulty: 'Stretch',
  },
  {
    id: 'identify-24',
    mode: 'identify',
    prompt: '“If the school does not buy our security system, the next incident will be on the principal’s conscience.”',
    correctFallacyId: 'appeal-to-fear',
    options: ['appeal-to-fear', 'slippery-slope', 'appeal-to-emotion'],
    explanation: 'The seller uses a frightening hypothetical and guilt to pressure a purchase without showing likelihood or whether this system is effective.',
    clue: 'A threat and personal blame replace a measured comparison of safeguards.',
    contrast: 'There is no chain of intermediate events, so slippery slope is too specific. Fear is the particular emotion being used.',
    difficulty: 'Warm-up',
  },
  {
    id: 'valid-01',
    mode: 'valid',
    prompt: 'The transit authority reports that buses on this route were late 18% of the time last month and explains that roadworks affected the schedule. It recommends checking the live timetable before leaving.',
    correctFallacyId: null,
    options: [],
    explanation: 'The claim is limited to a defined period and route, gives a measurable basis, and offers a plausible explanation. It does not claim that every bus is always late.',
    clue: 'Specific scope, visible evidence, and appropriately cautious wording.',
    contrast: 'A hasty generalization would jump from a few rides to every route. A causal fallacy would claim roadworks are the only possible cause without support.',
    difficulty: 'Warm-up',
  },
  {
    id: 'valid-02',
    mode: 'valid',
    prompt: 'I disagree with the author’s conclusion, but the paper includes a preregistered experiment, a control group, and the full dataset. We should examine the methods before deciding.',
    correctFallacyId: null,
    options: [],
    explanation: 'The speaker evaluates the evidence rather than the author’s identity and keeps the conclusion open until the method is examined.',
    clue: 'Disagreement is paired with a request to inspect relevant evidence.',
    contrast: 'This is not an appeal to authority because the paper is not accepted merely due to its author. The dataset and method are the reasons to investigate.',
    difficulty: 'Deep dive',
  },
  {
    id: 'valid-03',
    mode: 'valid',
    prompt: 'We already spent six months on the old tool, but it now costs twice as much to maintain as the replacement. Let’s compare the next year of costs rather than defend the time already spent.',
    correctFallacyId: null,
    options: [],
    explanation: 'This explicitly avoids the sunk-cost fallacy. Past effort is acknowledged as information, but the decision is based on costs and benefits that remain changeable.',
    clue: 'The speaker separates unrecoverable effort from the future decision.',
    contrast: 'The mention of six months is not itself fallacious. It becomes a fallacy only if the past investment is used to force continuation.',
    difficulty: 'Deep dive',
  },
  {
    id: 'valid-04',
    mode: 'valid',
    prompt: 'The pilot group improved after the training, but we should not claim the training caused the change until we compare it with a similar group that did not receive the training.',
    correctFallacyId: null,
    options: [],
    explanation: 'The speaker recognizes that improvement over time is not enough for a causal conclusion and proposes a relevant comparison.',
    clue: 'Uncertainty is preserved and an alternative explanation is addressed directly.',
    contrast: 'This is the opposite of correlation-causation or post hoc: the speaker refuses to make the causal leap without stronger design.',
    difficulty: 'Deep dive',
  },
  {
    id: 'valid-05',
    mode: 'valid',
    prompt: 'The chef recommends this knife for professional kitchens, but the review also lists the steel, warranty, maintenance requirements, and limitations. Those details let us assess the recommendation.',
    correctFallacyId: null,
    options: [],
    explanation: 'A recommendation from an experienced chef can be a useful data point when paired with reasons that readers can inspect. The authority is not treated as infallible.',
    clue: 'The source’s experience is relevant and the recommendation is supported with checkable details.',
    contrast: 'An appeal to authority would say the knife is good solely because a famous chef said so. Here, the evidence extends beyond status.',
    difficulty: 'Deep dive',
  },
  {
    id: 'valid-06',
    mode: 'valid',
    prompt: 'Our survey found that 62% of respondents prefer option A, but the sample came from existing customers, so we should not assume the whole market prefers it.',
    correctFallacyId: null,
    options: [],
    explanation: 'The speaker reports the result within its actual sample and warns against generalizing beyond it. That is careful reasoning, not a fallacy.',
    clue: 'The denominator and sampling limit are stated instead of hidden.',
    contrast: 'Cherry-picking would hide inconvenient results; hasty generalization would extend this customer sample to the entire market.',
    difficulty: 'Deep dive',
  },
  {
    id: 'valid-07',
    mode: 'valid',
    prompt: 'Three people on my street installed heat pumps and later had expensive repairs. Heat pumps are clearly unreliable, so nobody should buy one.',
    correctFallacyId: 'hasty-generalization',
    options: [],
    explanation: 'Three nearby experiences are not enough to judge every heat pump. The conclusion also ignores model, installation quality, age, and the experiences of owners without repairs.',
    clue: 'A small, possibly unusual sample is used to describe an entire category.',
    contrast: 'This is not cherry-picking unless the speaker deliberately selected those three cases from a larger set. The visible mistake is the jump from too few examples.',
    difficulty: 'Warm-up',
  },
  {
    id: 'valid-08',
    mode: 'valid',
    prompt: 'A famous novelist says the city’s bridge is structurally safe, so the engineering inspection is unnecessary.',
    correctFallacyId: 'appeal-to-authority',
    options: [],
    explanation: 'Writing expertise does not establish structural engineering expertise. The novelist’s fame is being used to replace the relevant inspection.',
    clue: 'A respected person is treated as decisive outside the domain that made them respected.',
    contrast: 'The statement could be reasonable if a qualified structural engineer explained the inspection results. Here, reputation is the only support.',
    difficulty: 'Warm-up',
  },
  {
    id: 'valid-09',
    mode: 'valid',
    prompt: 'The café changed its logo on Friday and weekend sales rose, so the new logo caused the increase.',
    correctFallacyId: 'post-hoc',
    options: [],
    explanation: 'The logo change came first, but a busy weekend, a promotion, weather, or ordinary variation could explain the rise. Timing alone does not isolate the cause.',
    clue: 'One event is credited because it happened immediately before another.',
    contrast: 'Correlation-causation is the wider family; post hoc is the sharper label for this single before-and-after story.',
    difficulty: 'Warm-up',
  },
  {
    id: 'valid-10',
    mode: 'valid',
    prompt: 'I asked for the source, then a full report, and now that you sent it I need a different study before I will even consider the claim.',
    correctFallacyId: 'moving-goalposts',
    options: [],
    explanation: 'The standard keeps changing after each requested item is supplied. A fair evaluation would say in advance what evidence could count and then assess it.',
    clue: 'The evidence threshold moves only after the previous threshold is met.',
    contrast: 'Burden of proof is about who should support a claim. This response refuses to let any agreed level of support count.',
    difficulty: 'Deep dive',
  },
  {
    id: 'scenario-01',
    mode: 'scenario',
    prompt: 'In a town-hall debate about a new bike lane, the council member says: “The pilot removes parking on one block during rush hour. If we approve it, next they will remove parking on every street, then cars will be banned from downtown, and local shops will collapse. We cannot take the first step.”',
    correctFallacyId: 'slippery-slope',
    options: ['slippery-slope', 'false-dilemma', 'strawman'],
    explanation: 'The argument does not assess the pilot on its own evidence. It treats several speculative policy and economic steps as inevitable, without showing what decisions or safeguards would sit between them.',
    clue: 'The argument asks you to reject a small trial because of an unproven chain of future outcomes.',
    contrast: 'There is an element of exaggeration, but the core error is the unsupported sequence. A false dilemma would claim the town has only two choices, which is not the main move here.',
    difficulty: 'Deep dive',
  },
  {
    id: 'scenario-02',
    mode: 'scenario',
    prompt: 'A marketing director presents six customer stories where a coaching package led to a promotion. When asked about customers who saw no change, she says: “Those cases are not useful for understanding what success looks like, so we left them out. The results prove the package works.”',
    correctFallacyId: 'cherry-picking',
    options: ['cherry-picking', 'survivorship-bias', 'anecdotal-evidence'],
    explanation: 'The director openly selects favorable stories and suppresses the outcomes that would calibrate the claim. The six stories may be genuine, but the presentation cannot support “the results” without the missing cases.',
    clue: 'The speaker admits that inconvenient outcomes were excluded before drawing the conclusion.',
    contrast: 'Survivorship bias would fit if failed cases disappeared from view because only survivors were visible. Here the selection is deliberate and explicit, so cherry-picking is the sharper diagnosis.',
    difficulty: 'Stretch',
  },
  {
    id: 'scenario-03',
    mode: 'scenario',
    prompt: 'During a team retro, an engineer says the release checklist missed a security step. The product lead responds: “You were the one who caused the outage last quarter. Until you can prove you never make mistakes, your criticism of this checklist does not count.”',
    correctFallacyId: 'tu-quoque',
    options: ['tu-quoque', 'ad-hominem', 'burden-of-proof'],
    explanation: 'The lead points to the engineer’s past mistake instead of checking whether the checklist missed a security step. The demand to prove perfect reliability also raises an unfair standard, but the attempted rebuttal is the hypocrisy attack.',
    clue: 'A relevant process concern is dismissed because the speaker has previously failed.',
    contrast: 'Ad hominem describes the broader personal attack, but tu quoque is the specific “you did it too” form. Burden of proof is secondary here, not the central diversion.',
    difficulty: 'Deep dive',
  },
  {
    id: 'scenario-04',
    mode: 'scenario',
    prompt: 'A health newsletter writes: “Readers who started our morning routine reported more energy after two weeks. The routine caused the improvement, and anyone who doubts it is ignoring the evidence.” The newsletter did not ask about sleep, illness, or other changes.',
    correctFallacyId: 'correlation-causation',
    options: ['correlation-causation', 'post-hoc', 'appeal-to-authority'],
    explanation: 'The report observes an association after people began a routine, then assigns the whole improvement to that routine without comparison or controls. Other changes and self-selection remain plausible explanations.',
    clue: 'A before-and-after self-report is treated as proof of a single cause.',
    contrast: 'The newsletter also uses a defensive tone, but no authority is the basis of the causal claim. Post hoc is related; the missing controls across a group make correlation-causation the more useful lesson.',
    difficulty: 'Deep dive',
  },
  {
    id: 'scenario-05',
    mode: 'scenario',
    prompt: 'A founder says: “We have spent €80,000 and a year building this feature. Canceling it now would waste everything, so we must keep adding staff until customers adopt it.” No one compares the remaining build cost with other ways to solve the customer problem.',
    correctFallacyId: 'sunk-cost',
    options: ['sunk-cost', 'appeal-to-emotion', 'moving-goalposts'],
    explanation: 'The past investment is treated as a reason to spend more, even though it cannot be recovered. The relevant question is which choice creates the best future outcome from today.',
    clue: 'The decision is anchored to unrecoverable money and time.',
    contrast: 'The language may evoke waste and regret, but the defining mistake is using the past spend to dictate the future. No evidence threshold is being changed.',
    difficulty: 'Warm-up',
  },
  {
    id: 'scenario-06',
    mode: 'scenario',
    prompt: 'A mayor announces a complex housing proposal: “Residents who oppose this either want rents to stay high or want the city to stop growing. There is no responsible middle position.” The proposal includes several different zoning and subsidy choices, but they are not discussed.',
    correctFallacyId: 'false-dilemma',
    options: ['false-dilemma', 'strawman', 'appeal-to-emotion'],
    explanation: 'The mayor reduces a multi-part policy debate to two motives and labels every alternative irresponsible. People could disagree about the design while still wanting affordability and growth.',
    clue: 'The opposition is forced into one of two motives even though the policy has multiple dimensions.',
    contrast: 'The opponents are framed unfairly, but the main structure is the missing middle: two options are presented as exhaustive when they are not.',
    difficulty: 'Deep dive',
  },
  {
    id: 'scenario-07',
    mode: 'scenario',
    prompt: 'A procurement officer asks a vendor to explain a three-month delay. The vendor answers: “Our company has supported local apprentices for ten years and won an ethics award. It would be unfair to focus on one late shipment.” The contract and delivery plan are never addressed.',
    correctFallacyId: 'red-herring',
    options: ['red-herring', 'appeal-to-emotion', 'false-equivalence'],
    explanation: 'The vendor supplies positive background that is unrelated to whether the delay breached the contract or how it will be fixed. The character of the company does not answer the operational question.',
    clue: 'True and flattering facts are used to pull the conversation away from the delay.',
    contrast: 'The appeal may create sympathy, but its primary function is distraction. No comparison between equal cases is made, so false equivalence is not the best fit.',
    difficulty: 'Warm-up',
  },
  {
    id: 'scenario-08',
    mode: 'scenario',
    prompt: 'A moderator says: “No real environmentalist flies for vacation.” A guest who campaigns for clean energy admits she flew to visit a sick parent. The moderator replies: “Then she is not a real environmentalist, whatever her other work says.”',
    correctFallacyId: 'no-true-scotsman',
    options: ['no-true-scotsman', 'false-equivalence', 'circular-reasoning'],
    explanation: 'The moderator adds an absolute purity condition only after meeting a counterexample. The category is redefined to preserve the original generalization instead of reconsidering it.',
    clue: 'A counterexample is excluded by an improvised definition of who counts as genuine.',
    contrast: 'The guest’s single flight could be debated, but the moderator’s reasoning is not that all flights are equal. It is a category-protection move.',
    difficulty: 'Stretch',
  },
]

export const fallacyById = Object.fromEntries(fallacies.map((fallacy) => [fallacy.id, fallacy])) as Record<string, Fallacy>
