export const categories = [
  'Relevance',
  'Presumption',
  'Ambiguity',
  'Causation',
  'Emotional reasoning',
  'Statistical fallacies',
  'Personal attacks',
] as const

export type Category = (typeof categories)[number]
export type Difficulty = 'Easy' | 'Medium' | 'Hard'

export const categoryLabels: Record<Category, string> = {
  Relevance: 'Relevance',
  Presumption: 'Presumption',
  Ambiguity: 'Ambiguity',
  Causation: 'Causation',
  'Emotional reasoning': 'Emotional reasoning',
  'Statistical fallacies': 'Statistical fallacies',
  'Personal attacks': 'Personal attacks',
}

export interface Fallacy {
  id: string
  nameEn: string
  nameNl: string
  category: Category
  difficulty: Difficulty
  definition: string
  explanation: string
  example: string
  extraExamples: string[]
  whyWrong: string
  signals: string[]
  confusedWith: string[]
}

export interface Question {
  id: string
  statement: string
  correctFallacyId: string | null
  difficulty: Difficulty
  category: Category | null
  explanation: string
  suspiciousPart: string
  contrast: string
  optionIds: string[]
}

export const fallacies: Fallacy[] = [
  {
    id: 'strawman',
    nameEn: 'Strawman',
    nameNl: 'Stroman',
    category: 'Relevance',
    difficulty: 'Easy',
    definition: 'Iemands argument versimpelen of verdraaien en daarna die zwakkere versie aanvallen.',
    explanation: 'Je reageert niet op wat de ander werkelijk zegt, maar op een makkelijkere versie ervan. Daardoor lijkt het alsof je het argument weerlegt terwijl je eigenlijk een nieuw argument hebt aangevallen.',
    example: 'A: We moeten minder vaak vliegen. B: Dus jij wilt dat niemand ooit meer op vakantie gaat?',
    extraExamples: [
      'Je stelt voor om vergaderingen korter te maken, dus je vindt overleg blijkbaar nutteloos.',
      'Zij wil de regels voor sociale media aanscherpen. Ze wil dus totale censuur.',
    ],
    whyWrong: 'De conclusie maakt het oorspronkelijke standpunt extremer dan het was. De spreker hoeft niet te reageren op het echte voorstel.',
    signals: ['Dus jij zegt eigenlijk dat...', 'Een gematigd standpunt extreem maken.', 'Een argument aanvallen dat niet is gemaakt.'],
    confusedWith: ['red-herring', 'false-dilemma'],
  },
  {
    id: 'red-herring',
    nameEn: 'Red herring',
    nameNl: 'Rode haring',
    category: 'Relevance',
    difficulty: 'Medium',
    definition: 'Een afleidend punt inbrengen dat niet antwoord geeft op de oorspronkelijke vraag.',
    explanation: 'Het nieuwe onderwerp kan op zichzelf interessant of waar zijn, maar het leidt de aandacht weg van de claim die besproken moest worden.',
    example: 'Waarom was het rapport te laat? Het team heeft dit jaar wel drie prijzen gewonnen.',
    extraExamples: [
      'De vraag gaat over de veiligheid van de auto, maar de verkoper begint over de lage onderhoudskosten.',
      'Waarom heb je mijn bericht niet beantwoord? We hebben toch een leuke vakantie gehad?',
    ],
    whyWrong: 'Het antwoord behandelt een ander onderwerp. Het zegt niets over de reden dat het rapport te laat was.',
    signals: ['Een zijpad na een kritische vraag.', 'Van onderwerp wisselen zonder het verband uit te leggen.', 'Een waar maar niet-relevant feit benadrukken.'],
    confusedWith: ['strawman', 'appeal-to-emotion'],
  },
  {
    id: 'appeal-to-authority',
    nameEn: 'Appeal to authority',
    nameNl: 'Beroep op autoriteit',
    category: 'Relevance',
    difficulty: 'Medium',
    definition: 'Een claim als waar behandelen omdat een bekende of deskundige hem zegt, zonder het bewijs te beoordelen.',
    explanation: 'Een expert kan een goede aanwijzing zijn, maar autoriteit vervangt geen argument. Het is vooral een probleem wanneer de persoon geen deskundige is op dit onderwerp of wanneer diens uitspraak het enige bewijs vormt.',
    example: 'Een beroemde voetballer zegt dat dit supplement werkt, dus het werkt.',
    extraExamples: [
      'Mijn docent zegt dat deze politieke voorspelling uitkomt, dus dat is zeker zo.',
      'Een Nobelprijswinnaar vindt deze film goed, dus de film is objectief goed.',
    ],
    whyWrong: 'De reputatie van de spreker bewijst de claim niet. Er is geen relevant onderzoek of argument gegeven.',
    signals: ['Een naam of titel als bewijs gebruiken.', 'Geen inhoudelijke reden naast de autoriteit.', 'Een expert buiten diens vakgebied opvoeren.'],
    confusedWith: ['red-herring', 'appeal-to-popularity'],
  },
  {
    id: 'ad-hominem',
    nameEn: 'Ad hominem',
    nameNl: 'Op de man spelen',
    category: 'Personal attacks',
    difficulty: 'Easy',
    definition: 'De persoon aanvallen in plaats van het argument te beantwoorden.',
    explanation: 'De eigenschappen, achtergrond of het karakter van de spreker zeggen niet automatisch iets over de waarheid van diens argument.',
    example: 'Je kunt zijn economische argument niet serieus nemen. Hij woont nog bij zijn ouders.',
    extraExamples: [
      'Jij hebt niet eens een diploma, dus jouw mening over klimaatverandering telt niet.',
      'Ze is een arrogante blogger; haar uitleg over de cijfers is onzin.',
    ],
    whyWrong: 'De persoonlijke aanval vervangt een antwoord op het economische argument.',
    signals: ['Scheldwoorden of karakteroordelen.', 'Een irrelevante eigenschap van de spreker.', 'De inhoud van het argument blijft onbeantwoord.'],
    confusedWith: ['tu-quoque', 'guilt-by-association'],
  },
  {
    id: 'tu-quoque',
    nameEn: 'Tu quoque',
    nameNl: 'Jij-bak',
    category: 'Personal attacks',
    difficulty: 'Easy',
    definition: 'Een kritiek afwijzen door te zeggen dat de ander zelf hetzelfde doet.',
    explanation: 'De beschuldiging kan nog steeds waar zijn, ook als de persoon die hem uit niet consequent is. Hypocrisie weerlegt het oorspronkelijke punt niet.',
    example: 'Je moet minder suiker eten. Jij drinkt zelf elke dag frisdrank!',
    extraExamples: [
      'Je mag niet te laat komen. Jij was vorige week ook te laat.',
      'Je zegt dat liegen verkeerd is, maar je hebt zelf ooit gelogen.',
    ],
    whyWrong: 'De spreker reageert niet op de inhoud van de kritiek, maar wijst naar het gedrag van de ander.',
    signals: ['Jij doet het zelf ook.', 'De aandacht verschuift naar de criticus.', 'Geen inhoudelijk antwoord op de oorspronkelijke claim.'],
    confusedWith: ['ad-hominem', 'guilt-by-association'],
  },
  {
    id: 'guilt-by-association',
    nameEn: 'Guilt by association',
    nameNl: 'Schuld door associatie',
    category: 'Personal attacks',
    difficulty: 'Medium',
    definition: 'Een persoon of idee afwijzen omdat het wordt verbonden aan iemand of iets dat negatief wordt gevonden.',
    explanation: 'Een relatie of gedeelde eigenschap bewijst niet dat iemand dezelfde slechte bedoelingen of eigenschappen heeft.',
    example: 'Die onderzoeker staat op dezelfde conferentie als complotdenkers, dus haar onderzoek deugt niet.',
    extraExamples: [
      'Hij zit in dezelfde groepschat als fraudeurs, dus hij is vast ook oneerlijk.',
      'Deze methode komt uit een bedrijf dat fouten maakte, dus de methode is waardeloos.',
    ],
    whyWrong: 'De kwaliteit van het argument wordt niet onderzocht. Alleen de associatie wordt aangevallen.',
    signals: ['Hij hoort bij die groep.', 'Een gedeelde locatie, bron of vriend als bewijs.', 'Negatieve reputatie overschaduwt de inhoud.'],
    confusedWith: ['ad-hominem', 'appeal-to-authority'],
  },
  {
    id: 'appeal-to-emotion',
    nameEn: 'Appeal to emotion',
    nameNl: 'Beroep op emotie',
    category: 'Emotional reasoning',
    difficulty: 'Easy',
    definition: 'Een gevoel gebruiken als vervanging voor bewijs of een inhoudelijk argument.',
    explanation: 'Emoties zijn echt en kunnen relevant zijn, maar ze maken een bewering niet automatisch waar. De emotionele druk leidt af van wat er bewezen moet worden.',
    example: 'Als je echt om je familie geeft, steun je dit plan.',
    extraExamples: [
      'Je wilt toch geen harteloos persoon lijken? Geef mij daarom de baan.',
      'Iedereen die van dieren houdt, moet dit voorstel steunen.',
    ],
    whyWrong: 'De spreker probeert instemming te krijgen via schuldgevoel of liefde, niet via redenen voor het plan.',
    signals: ['Als je echt om X geeft...', 'Schuld, schaamte of medelijden oproepen.', 'Gevoel als bewijs presenteren.'],
    confusedWith: ['appeal-to-fear', 'red-herring'],
  },
  {
    id: 'appeal-to-fear',
    nameEn: 'Appeal to fear',
    nameNl: 'Beroep op angst',
    category: 'Emotional reasoning',
    difficulty: 'Easy',
    definition: 'Angst voor een mogelijk gevolg inzetten om een claim te laten accepteren zonder bewijs.',
    explanation: 'Een risico kan serieus zijn, maar alleen angst bewijst niet dat de voorgestelde oplossing werkt of noodzakelijk is.',
    example: 'Als we deze app niet kopen, worden we binnen een jaar ingehaald door alle concurrenten.',
    extraExamples: [
      'Als je niet voor dit beleid stemt, is de stad binnenkort volledig onveilig.',
      'Stop nu met vragen stellen, anders gaat alles mis.',
    ],
    whyWrong: 'Het dreigende scenario wordt als zekerheid gebracht en er wordt geen onderbouwing gegeven voor de oplossing.',
    signals: ['Anders gebeurt er iets verschrikkelijks.', 'Een onwaarschijnlijke ramp als zekerheid.', 'Urgentie gebruiken om bewijs over te slaan.'],
    confusedWith: ['slippery-slope', 'appeal-to-emotion'],
  },
  {
    id: 'appeal-to-popularity',
    nameEn: 'Appeal to popularity',
    nameNl: 'Beroep op populariteit',
    category: 'Emotional reasoning',
    difficulty: 'Easy',
    definition: 'Beweren dat iets waar of goed is omdat veel mensen het geloven of doen.',
    explanation: 'Populariteit kan een aanwijzing zijn voor smaak of bereik, maar veel mensen kunnen zich ook vergissen.',
    example: 'Miljoenen mensen gebruiken dit dieet, dus het moet gezond zijn.',
    extraExamples: [
      'Iedereen in mijn klas vindt deze uitleg goed, dus hij is correct.',
      'Het is de populairste browser, dus hij is de veiligste.',
    ],
    whyWrong: 'Het aantal aanhangers is geen bewijs voor de waarheid of kwaliteit van de claim.',
    signals: ['Iedereen doet het.', 'Miljoenen mensen kunnen niet fout zitten.', 'Populariteit als kwaliteitsbewijs.'],
    confusedWith: ['appeal-to-authority', 'appeal-to-emotion'],
  },
  {
    id: 'false-dilemma',
    nameEn: 'False dilemma',
    nameNl: 'Valse tweedeling',
    category: 'Presumption',
    difficulty: 'Easy',
    definition: 'Doen alsof er maar twee keuzes zijn terwijl er meer mogelijkheden bestaan.',
    explanation: 'Door opties weg te laten lijkt een keuze onvermijdelijk. De ontbrekende tussenposities of alternatieven worden niet onderzocht.',
    example: 'Je bent voor ons plan of je geeft blijkbaar niets om het team.',
    extraExamples: [
      'Of we verbieden telefoons volledig, of niemand leert nog iets.',
      'Je kunt alleen hard werken of lui zijn; een middenweg bestaat niet.',
    ],
    whyWrong: 'Er zijn meer mogelijkheden dan volledig steunen of niets geven om het team.',
    signals: ['Of... of...', 'Slechts twee uitersten aanbieden.', 'Een gematigde optie wegdrukken.'],
    confusedWith: ['strawman', 'slippery-slope'],
  },
  {
    id: 'slippery-slope',
    nameEn: 'Slippery slope',
    nameNl: 'Glijdende schaal',
    category: 'Presumption',
    difficulty: 'Medium',
    definition: 'Beweren dat een kleine stap onvermijdelijk leidt tot een reeks extreme gevolgen.',
    explanation: 'Een keten van gevolgen kan bestaan, maar elk verband en elke stap moet worden onderbouwd. Onvermijdelijkheid wordt hier meestal alleen verondersteld.',
    example: 'Als we een deadline een dag verschuiven, vraagt straks niemand meer om deadlines en stort het hele project in.',
    extraExamples: [
      'Als kinderen een uur langer gamen, willen ze straks nooit meer naar school.',
      'We laten een uitzondering toe en voor je het weet gelden er helemaal geen regels meer.',
    ],
    whyWrong: 'De tussenstappen zijn niet bewezen en het extreme eindpunt wordt als onvermijdelijk gepresenteerd.',
    signals: ['En dan straks...', 'Voor je het weet...', 'Een lange keten zonder bewijs per stap.'],
    confusedWith: ['appeal-to-fear', 'false-cause'],
  },
  {
    id: 'loaded-question',
    nameEn: 'Loaded question',
    nameNl: 'Beladen vraag',
    category: 'Presumption',
    difficulty: 'Medium',
    definition: 'Een vraag stellen waarin al een onbewezen of nadelige aanname zit.',
    explanation: 'Elke ja- of nee-reactie accepteert de verborgen aanname. De vraag moet eerst worden opgesplitst voordat hij eerlijk kan worden beantwoord.',
    example: 'Wanneer stop je eindelijk met je team in de steek laten?',
    extraExamples: [
      'Waarom blijf je liegen tegen je klanten?',
      'Hoeveel geld heb je verspild aan dat mislukte project?',
    ],
    whyWrong: 'De vraag veronderstelt al dat de persoon het team in de steek laat.',
    signals: ['Eindelijk', 'Nog steeds', 'Een beschuldiging verborgen in de vraag.'],
    confusedWith: ['begging-the-question', 'ad-hominem'],
  },
  {
    id: 'begging-the-question',
    nameEn: 'Begging the question',
    nameNl: 'Cirkelredenering',
    category: 'Presumption',
    difficulty: 'Medium',
    definition: 'De conclusie al aannemen in de premisse die haar zou moeten bewijzen.',
    explanation: 'De redenering klinkt alsof er bewijs wordt gegeven, maar gebruikt in andere woorden dezelfde claim als uitgangspunt.',
    example: 'Deze regel is eerlijk omdat het een eerlijke regel is.',
    extraExamples: [
      'De krant is betrouwbaar omdat zij alleen betrouwbare informatie publiceert.',
      'Ik heb gelijk, want ik zeg nooit iets dat fout is.',
    ],
    whyWrong: 'Er wordt geen onafhankelijk bewijs toegevoegd. De conclusie is slechts herhaald.',
    signals: ['Omdat het zo is.', 'Dezelfde woorden keren terug als reden en conclusie.', 'Geen externe grond voor de claim.'],
    confusedWith: ['loaded-question', 'appeal-to-authority'],
  },
  {
    id: 'no-true-scotsman',
    nameEn: 'No true Scotsman',
    nameNl: 'Geen echte Schot',
    category: 'Presumption',
    difficulty: 'Hard',
    definition: 'Een groep achteraf zo definieren dat tegenvoorbeelden niet meer meetellen.',
    explanation: 'Wanneer iemand een tegenvoorbeeld geeft, wordt de definitie aangepast met een extra eis. Zo wordt de claim onweerlegbaar gemaakt.',
    example: 'Geen echte natuurliefhebber rijdt ooit met de auto. Die persoon rijdt? Dan is hij geen echte natuurliefhebber.',
    extraExamples: [
      'Een echte ondernemer maakt nooit een fout; wie failliet gaat was dus geen echte ondernemer.',
      'Geen echte fan mist een wedstrijd. Dan was je blijkbaar geen echte fan.',
    ],
    whyWrong: 'De spreker verandert de betekenis van de groep alleen om het tegenvoorbeeld buiten te sluiten.',
    signals: ['Geen echte...', 'De definitie verschuift na een tegenvoorbeeld.', 'Een ideaalbeeld als lidmaatschapsregel.'],
    confusedWith: ['equivocation', 'hasty-generalization'],
  },
  {
    id: 'equivocation',
    nameEn: 'Equivocation',
    nameNl: 'Betekenisverschuiving',
    category: 'Ambiguity',
    difficulty: 'Hard',
    definition: 'Een woord tijdens de redenering ongemerkt in twee verschillende betekenissen gebruiken.',
    explanation: 'De zinnen lijken logisch verbonden omdat hetzelfde woord terugkomt. De betekenis van dat woord is echter verschoven.',
    example: 'Niets is beter dan vrijheid. Een boterham is beter dan niets. Dus een boterham is beter dan vrijheid.',
    extraExamples: [
      'Een bank is veilig. Deze bank staat buiten. Dus buiten staan is veilig.',
      'Het recht staat aan mijn kant; rechtsaf is dus de juiste richting.',
    ],
    whyWrong: 'Het woord niets, bank of recht betekent in de twee zinnen niet hetzelfde.',
    signals: ['Hetzelfde woord lijkt de brug te vormen.', 'Een abstracte en concrete betekenis door elkaar.', 'De conclusie voelt logisch maar wringt bij definities.'],
    confusedWith: ['no-true-scotsman', 'composition-fallacy'],
  },
  {
    id: 'false-cause',
    nameEn: 'False cause',
    nameNl: 'Valse oorzaak',
    category: 'Causation',
    difficulty: 'Medium',
    definition: 'Een oorzaak-gevolgrelatie aannemen zonder voldoende bewijs voor het causale verband.',
    explanation: 'Dat twee dingen samen voorkomen betekent niet dat het ene het andere veroorzaakt. Er kunnen andere verklaringen of toeval in het spel zijn.',
    example: 'Sinds ik mijn nieuwe schoenen draag, win ik vaker. De schoenen maken mij dus beter.',
    extraExamples: [
      'De verkoop steeg nadat de nieuwe kleur werd gelanceerd, dus alleen de kleur veroorzaakte de groei.',
      'De haan kraait voordat de zon opkomt, dus zijn gekraai laat de zon opkomen.',
    ],
    whyWrong: 'Er is geen controle voor toeval, andere veranderingen of omgekeerde causaliteit.',
    signals: ['Sindsdien, dus daardoor.', 'Een gebeurtenis wordt direct als oorzaak aangewezen.', 'Andere mogelijke oorzaken ontbreken.'],
    confusedWith: ['post-hoc', 'correlation-causation'],
  },
  {
    id: 'post-hoc',
    nameEn: 'Post hoc ergo propter hoc',
    nameNl: 'Na dit, dus door dit',
    category: 'Causation',
    difficulty: 'Easy',
    definition: 'Aannemen dat de eerste gebeurtenis de oorzaak is van de tweede alleen omdat zij eerder gebeurde.',
    explanation: 'Volgorde alleen is geen bewijs voor causaliteit. De tweede gebeurtenis kan vanzelf of door iets anders zijn ontstaan.',
    example: 'Ik droeg mijn gelukssokken en daarna wonnen we. De sokken hebben de wedstrijd gewonnen.',
    extraExamples: [
      'Na de vergadering begon het te regenen, dus de vergadering veroorzaakte de regen.',
      'Ik nam een vitamine en voelde me later beter; de vitamine heeft mij genezen.',
    ],
    whyWrong: 'Er is alleen een tijdsvolgorde genoemd, geen bewijs dat de sokken of vitamine het gevolg veroorzaakten.',
    signals: ['Daarna gebeurde...', 'Sinds ik...', 'Tijdvolgorde verwarren met oorzaak.'],
    confusedWith: ['false-cause', 'correlation-causation'],
  },
  {
    id: 'correlation-causation',
    nameEn: 'Correlation implies causation',
    nameNl: 'Correlatie is causaliteit',
    category: 'Causation',
    difficulty: 'Hard',
    definition: 'Een statistische samenhang behandelen alsof bewezen is dat het ene het andere veroorzaakt.',
    explanation: 'Correlatie vertelt dat twee variabelen samen bewegen. Zonder experiment of extra bewijs weet je niet of A B veroorzaakt, B A veroorzaakt of een derde factor beide veroorzaakt.',
    example: 'In wijken met meer brandweerlieden is er meer brandschade. Brandweerlieden veroorzaken dus schade.',
    extraExamples: [
      'IJsverkoop en zonnebrand nemen tegelijk toe, dus ijs veroorzaakt zonnebrand.',
      'Mensen met meer apps slapen minder; apps zijn daarom de enige oorzaak.',
    ],
    whyWrong: 'De ernst van de brand veroorzaakt zowel meer schade als de inzet van meer brandweerlieden.',
    signals: ['Tegelijk stijgen, dus...', 'Een grafiek zonder verklaring.', 'Een derde factor blijft buiten beeld.'],
    confusedWith: ['false-cause', 'post-hoc'],
  },
  {
    id: 'hasty-generalization',
    nameEn: 'Hasty generalization',
    nameNl: 'Overhaaste generalisatie',
    category: 'Statistical fallacies',
    difficulty: 'Easy',
    definition: 'Een brede conclusie trekken uit te weinig of ongeschikte voorbeelden.',
    explanation: 'Een voorbeeld kan echt zijn, maar een kleine of scheve steekproef zegt weinig over de hele groep.',
    example: 'Twee toeristen uit die stad waren onbeleefd. Mensen uit die stad zijn dus onbeleefd.',
    extraExamples: [
      'Mijn eerste online les was saai, dus online onderwijs werkt niet.',
      'Een werknemer maakte een fout; deze afdeling kan blijkbaar niet werken.',
    ],
    whyWrong: 'Twee personen vormen geen representatieve steekproef voor een hele stad.',
    signals: ['Een of enkele voorbeelden.', 'Iedereen, altijd of nooit na een klein aantal gevallen.', 'Geen informatie over de steekproef.'],
    confusedWith: ['anecdotal-evidence', 'cherry-picking'],
  },
  {
    id: 'cherry-picking',
    nameEn: 'Cherry picking',
    nameNl: 'Kersenplukken',
    category: 'Statistical fallacies',
    difficulty: 'Medium',
    definition: 'Alleen de voorbeelden of cijfers kiezen die een conclusie steunen en de rest weglaten.',
    explanation: 'De gekozen data kunnen correct zijn, maar het weglaten van relevante tegeninformatie geeft een misleidend beeld.',
    example: 'Kijk naar deze drie dagen waarop onze omzet steeg. Ons nieuwe plan werkt duidelijk perfect.',
    extraExamples: [
      'Een dieetboek toont vijf succesvolle lezers en noemt de uitvallers niet.',
      'De grafiek begint op het hoogste punt zodat de daling onzichtbaar blijft.',
    ],
    whyWrong: 'De overige dagen en resultaten zijn nodig om de totale trend te beoordelen.',
    signals: ['Alleen de beste voorbeelden.', 'Geen volledige periode of dataset.', 'Tegenbewijs wordt niet genoemd.'],
    confusedWith: ['hasty-generalization', 'survivorship-bias'],
  },
  {
    id: 'anecdotal-evidence',
    nameEn: 'Anecdotal evidence',
    nameNl: 'Anekdotisch bewijs',
    category: 'Statistical fallacies',
    difficulty: 'Easy',
    definition: 'Een persoonlijke ervaring gebruiken als doorslaggevend bewijs voor een algemene claim.',
    explanation: 'Ervaringen kunnen een vraag opleveren, maar ze controleren niet voor toeval, selectie of andere verklaringen.',
    example: 'Mijn opa rookte en werd 95, dus roken is niet ongezond.',
    extraExamples: [
      'Mijn buurman werd rijk met crypto, dus iedereen kan daar makkelijk rijk mee worden.',
      'Ik dronk thee en mijn hoofdpijn ging weg, dus thee geneest hoofdpijn.',
    ],
    whyWrong: 'Een individuele uitzondering zegt weinig over het gemiddelde risico of resultaat.',
    signals: ['Mijn vriend...', 'Ik ken iemand die...', 'Een verhaal vervangt onderzoek of een grotere steekproef.'],
    confusedWith: ['hasty-generalization', 'cherry-picking'],
  },
  {
    id: 'gambler-fallacy',
    nameEn: "Gambler's fallacy",
    nameNl: 'Gokkersmisvatting',
    category: 'Statistical fallacies',
    difficulty: 'Medium',
    definition: 'Aannemen dat een onafhankelijke kansuitkomst moet omslaan omdat eerdere uitkomsten anders waren.',
    explanation: 'Bij onafhankelijke gebeurtenissen verandert de kans niet door de geschiedenis. Een reeks maakt de volgende uitkomst niet automatisch verschuldigd.',
    example: 'De munt is vijf keer kop gevallen, dus nu moet het munt zijn.',
    extraExamples: [
      'Deze loterijnummers zijn lang niet getrokken; ze zijn nu extra waarschijnlijk.',
      'De speler heeft drie keer gemist, dus zijn volgende schot gaat er zeker in.',
    ],
    whyWrong: 'Bij een eerlijke munt blijft de kans op kop of munt per worp hetzelfde.',
    signals: ['Het moet nu wel...', 'Achterstallige uitkomst.', 'Onafhankelijke gebeurtenissen behandelen alsof ze elkaar compenseren.'],
    confusedWith: ['false-cause', 'hasty-generalization'],
  },
  {
    id: 'survivorship-bias',
    nameEn: 'Survivorship bias',
    nameNl: 'Overlevingsbias',
    category: 'Statistical fallacies',
    difficulty: 'Hard',
    definition: 'Alleen de zichtbare succesgevallen bekijken en de onzichtbare mislukkingen vergeten.',
    explanation: 'De overblijvers zijn niet altijd representatief voor de hele groep. Zonder de uitvallers weet je niet welke eigenschappen echt hielpen.',
    example: 'Alle succesvolle ondernemers begonnen zonder plan, dus een plan hebben is onnodig.',
    extraExamples: [
      'De bekende schrijvers werkten s nachts, dus nachtwerk maakt je een goede schrijver.',
      'We bekijken alleen de startups die doorgroeiden en concluderen dat hun eerste idee altijd goed was.',
    ],
    whyWrong: 'De vele ondernemers of schrijvers die dezelfde aanpak volgden maar niet succesvol werden ontbreken.',
    signals: ['Kijk naar de winnaars.', 'Succesverhalen zonder mislukkingen.', 'De selectie achter de data blijft onzichtbaar.'],
    confusedWith: ['cherry-picking', 'anecdotal-evidence'],
  },
  {
    id: 'composition-fallacy',
    nameEn: 'Composition fallacy',
    nameNl: 'Compositiefout',
    category: 'Ambiguity',
    difficulty: 'Hard',
    definition: 'Aannemen dat wat voor losse onderdelen geldt automatisch ook voor het geheel geldt.',
    explanation: 'Eigenschappen van onderdelen kunnen veranderen wanneer ze samenkomen. Het geheel heeft soms nieuwe effecten of beperkingen.',
    example: 'Elke speler van dit team is uitstekend, dus het team zal zeker uitstekend samenwerken.',
    extraExamples: [
      'Elke steen in deze muur is licht, dus de hele muur is licht.',
      'Iedere medewerker is snel, dus het hele proces is snel.',
    ],
    whyWrong: 'Samenwerking en schaal kunnen het resultaat veranderen; individuele kwaliteit garandeert geen teamresultaat.',
    signals: ['Elk onderdeel, dus het geheel.', 'Eigenschap van deel naar systeem kopieren.', 'Samenwerking of schaal wordt genegeerd.'],
    confusedWith: ['equivocation', 'hasty-generalization'],
  },
]

export const questions: Question[] = [
  {
    id: 'q-strawman-1',
    statement: 'A: We moeten minder vaak vliegen. B: Dus jij wilt dat niemand ooit meer op vakantie gaat?',
    correctFallacyId: 'strawman',
    difficulty: 'Easy',
    category: 'Relevance',
    explanation: 'B maakt van "minder vaak vliegen" het veel extremere standpunt "nooit meer op vakantie".',
    suspiciousPart: 'Dus jij wilt dat niemand ooit meer op vakantie gaat?',
    contrast: 'Dit is geen red herring: B blijft bij het onderwerp, maar verdraait het standpunt. Het is ook geen valse tweedeling, want de kernfout is de verdraaiing.',
    optionIds: ['strawman', 'red-herring', 'false-dilemma'],
  },
  {
    id: 'q-ad-hominem-1',
    statement: 'Je kunt zijn economische argument niet serieus nemen. Hij woont nog bij zijn ouders.',
    correctFallacyId: 'ad-hominem',
    difficulty: 'Easy',
    category: 'Personal attacks',
    explanation: 'Het wonen bij zijn ouders zegt niets over de juistheid van zijn economische argument.',
    suspiciousPart: 'Hij woont nog bij zijn ouders.',
    contrast: 'Dit is geen tu quoque, want de spreker verwijt de ander niet dat hij hetzelfde doet. Het is een persoonlijke aanval.',
    optionIds: ['ad-hominem', 'tu-quoque', 'guilt-by-association'],
  },
  {
    id: 'q-authority-1',
    statement: 'Een beroemde voetballer zegt dat dit supplement werkt, dus het werkt.',
    correctFallacyId: 'appeal-to-authority',
    difficulty: 'Easy',
    category: 'Relevance',
    explanation: 'De voetballer wordt als bewijs gebruikt zonder dat er relevant onderzoek naar het supplement wordt gegeven.',
    suspiciousPart: 'Een beroemde voetballer zegt dat dit supplement werkt',
    contrast: 'Populariteit gaat over hoeveel mensen iets geloven. Hier draait de redenering om de status van een specifieke persoon.',
    optionIds: ['appeal-to-authority', 'appeal-to-popularity', 'anecdotal-evidence'],
  },
  {
    id: 'q-false-cause-1',
    statement: 'Sinds ik mijn nieuwe schoenen draag, win ik vaker. De schoenen maken mij dus beter.',
    correctFallacyId: 'false-cause',
    difficulty: 'Easy',
    category: 'Causation',
    explanation: 'De volgorde of samenhang bewijst niet dat de schoenen de oorzaak zijn van de betere resultaten.',
    suspiciousPart: 'De schoenen maken mij dus beter.',
    contrast: 'Post hoc is een specifieke vorm waarbij alleen de volgorde wordt gebruikt. Hier wordt breder een oorzaak geconcludeerd zonder andere verklaringen te onderzoeken.',
    optionIds: ['false-cause', 'post-hoc', 'correlation-causation'],
  },
  {
    id: 'q-tu-quoque-1',
    statement: 'Je moet minder suiker eten. Jij drinkt zelf elke dag frisdrank!',
    correctFallacyId: 'tu-quoque',
    difficulty: 'Easy',
    category: 'Personal attacks',
    explanation: 'De spreker reageert niet op de gezondheidsclaim, maar wijst op de inconsequentie van de ander.',
    suspiciousPart: 'Jij drinkt zelf elke dag frisdrank!',
    contrast: 'Het is geen gewone ad hominem: de aanval gaat specifiek over hetzelfde gedrag waarover de ander kritiek geeft.',
    optionIds: ['tu-quoque', 'ad-hominem', 'red-herring'],
  },
  {
    id: 'q-no-fallacy-1',
    statement: 'De plant groeide sneller in de kas omdat hij daar meer licht en water kreeg dan de planten buiten.',
    correctFallacyId: null,
    difficulty: 'Easy',
    category: null,
    explanation: 'Dit is een gewone, toetsbare verklaring. De spreker benoemt twee relevante verschillen en trekt geen overdreven conclusie.',
    suspiciousPart: 'omdat hij daar meer licht en water kreeg',
    contrast: 'Er wordt geen persoonlijke aanval, afleiding of onbewezen sprong gemaakt. Een plausibele verklaring is op zichzelf geen drogreden.',
    optionIds: ['false-cause', 'cherry-picking', 'appeal-to-authority'],
  },
  {
    id: 'q-false-dilemma-1',
    statement: 'Je bent voor ons plan of je geeft blijkbaar niets om het team.',
    correctFallacyId: 'false-dilemma',
    difficulty: 'Easy',
    category: 'Presumption',
    explanation: 'Er zijn meer opties dan het plan volledig steunen of niets om het team geven.',
    suspiciousPart: 'Je bent voor ons plan of je geeft blijkbaar niets om het team.',
    contrast: 'Dit is niet alleen emotionele druk: de hoofdstructuur presenteert twee onterechte uitersten als de enige opties.',
    optionIds: ['false-dilemma', 'appeal-to-emotion', 'strawman'],
  },
  {
    id: 'q-red-herring-1',
    statement: 'Waarom was het rapport te laat? Het team heeft dit jaar wel drie prijzen gewonnen.',
    correctFallacyId: 'red-herring',
    difficulty: 'Medium',
    category: 'Relevance',
    explanation: 'De prijzen kunnen waar zijn, maar ze beantwoorden niet waarom het rapport te laat was.',
    suspiciousPart: 'Het team heeft dit jaar wel drie prijzen gewonnen.',
    contrast: 'Er wordt geen standpunt verdraaid en niemand wordt aangevallen; de aandacht verschuift simpelweg naar een ander onderwerp.',
    optionIds: ['red-herring', 'strawman', 'ad-hominem'],
  },
  {
    id: 'q-slippery-1',
    statement: 'Als we een deadline een dag verschuiven, vraagt straks niemand meer om deadlines en stort het hele project in.',
    correctFallacyId: 'slippery-slope',
    difficulty: 'Medium',
    category: 'Presumption',
    explanation: 'Een kleine wijziging wordt zonder bewijs verbonden aan een reeks extreme en onvermijdelijke gevolgen.',
    suspiciousPart: 'vraagt straks niemand meer om deadlines en stort het hele project in',
    contrast: 'Angst speelt mee, maar de kenmerkende fout is de onbewezen keten van stappen. Daarom is glijdende schaal de beste diagnose.',
    optionIds: ['slippery-slope', 'appeal-to-fear', 'false-cause'],
  },
  {
    id: 'q-loaded-1',
    statement: 'Wanneer stop je eindelijk met je team in de steek laten?',
    correctFallacyId: 'loaded-question',
    difficulty: 'Medium',
    category: 'Presumption',
    explanation: 'De vraag veronderstelt al dat de aangesprokene het team in de steek laat.',
    suspiciousPart: 'Wanneer stop je eindelijk met je team in de steek laten?',
    contrast: 'Dit is geen ad hominem omdat de kern niet alleen een belediging is; het is een vraag die een beschuldiging als feit verpakt.',
    optionIds: ['loaded-question', 'ad-hominem', 'begging-the-question'],
  },
  {
    id: 'q-circular-1',
    statement: 'Deze regel is eerlijk omdat het een eerlijke regel is.',
    correctFallacyId: 'begging-the-question',
    difficulty: 'Medium',
    category: 'Presumption',
    explanation: 'De conclusie wordt opnieuw gebruikt als reden. Er is geen onafhankelijk bewijs voor de eerlijkheid.',
    suspiciousPart: 'omdat het een eerlijke regel is',
    contrast: 'Een beladen vraag verbergt een aanname in een vraag. Hier zit de aanname in een redenering die haar eigen conclusie herhaalt.',
    optionIds: ['begging-the-question', 'loaded-question', 'appeal-to-authority'],
  },
  {
    id: 'q-equivocation-1',
    statement: 'Niets is beter dan vrijheid. Een boterham is beter dan niets. Dus een boterham is beter dan vrijheid.',
    correctFallacyId: 'equivocation',
    difficulty: 'Hard',
    category: 'Ambiguity',
    explanation: 'Het woord "niets" betekent eerst geen enkel ding en daarna het ontbreken van een boterham. De betekenis verschuift.',
    suspiciousPart: 'Een boterham is beter dan niets. Dus een boterham is beter dan vrijheid.',
    contrast: 'De zinnen zijn niet vooral te weinig data of te emotioneel; de logische brug werkt alleen door de dubbele betekenis van "niets".',
    optionIds: ['equivocation', 'composition-fallacy', 'false-dilemma'],
  },
  {
    id: 'q-posthoc-1',
    statement: 'Ik droeg mijn gelukssokken en daarna wonnen we. De sokken hebben de wedstrijd gewonnen.',
    correctFallacyId: 'post-hoc',
    difficulty: 'Easy',
    category: 'Causation',
    explanation: 'De sokken kwamen eerder, maar dat bewijst niet dat zij de overwinning veroorzaakten.',
    suspiciousPart: 'en daarna wonnen we. De sokken hebben de wedstrijd gewonnen.',
    contrast: 'Een algemene valse oorzaak kan allerlei oorzaken verkeerd aanwijzen. Hier is de specifieke fout dat na elkaar gebeurde als oorzaak wordt gelezen.',
    optionIds: ['post-hoc', 'false-cause', 'gambler-fallacy'],
  },
  {
    id: 'q-correlation-1',
    statement: 'In wijken met meer brandweerlieden is er meer brandschade. Brandweerlieden veroorzaken dus schade.',
    correctFallacyId: 'correlation-causation',
    difficulty: 'Hard',
    category: 'Causation',
    explanation: 'De ernst van de brand kan zowel de schade als het aantal ingezette brandweerlieden verklaren.',
    suspiciousPart: 'Brandweerlieden veroorzaken dus schade.',
    contrast: 'Dit gaat expliciet over een samenhang in groepen of data. De fout is niet alleen dat de brandweerlieden eerder kwamen.',
    optionIds: ['correlation-causation', 'false-cause', 'post-hoc'],
  },
  {
    id: 'q-generalization-1',
    statement: 'Twee toeristen uit die stad waren onbeleefd. Mensen uit die stad zijn dus onbeleefd.',
    correctFallacyId: 'hasty-generalization',
    difficulty: 'Easy',
    category: 'Statistical fallacies',
    explanation: 'Twee voorbeelden vormen geen representatieve basis voor een uitspraak over alle inwoners.',
    suspiciousPart: 'Mensen uit die stad zijn dus onbeleefd.',
    contrast: 'Het kan ook anekdotisch bewijs zijn, maar de belangrijkste sprong hier is van een minieme steekproef naar de hele groep.',
    optionIds: ['hasty-generalization', 'anecdotal-evidence', 'cherry-picking'],
  },
  {
    id: 'q-cherry-1',
    statement: 'Kijk naar deze drie dagen waarop onze omzet steeg. Ons nieuwe plan werkt duidelijk perfect.',
    correctFallacyId: 'cherry-picking',
    difficulty: 'Medium',
    category: 'Statistical fallacies',
    explanation: 'Alleen de gunstige dagen worden getoond; de rest van de periode blijft buiten beeld.',
    suspiciousPart: 'Kijk naar deze drie dagen waarop onze omzet steeg.',
    contrast: 'De claim gebruikt niet zomaar te weinig voorbeelden, maar selecteert juist de voorbeelden die de gewenste conclusie ondersteunen.',
    optionIds: ['cherry-picking', 'hasty-generalization', 'survivorship-bias'],
  },
  {
    id: 'q-anecdote-1',
    statement: 'Mijn opa rookte en werd 95, dus roken is niet ongezond.',
    correctFallacyId: 'anecdotal-evidence',
    difficulty: 'Easy',
    category: 'Statistical fallacies',
    explanation: 'Een individuele ervaring zegt weinig over het gemiddelde gezondheidsrisico van roken.',
    suspiciousPart: 'Mijn opa rookte en werd 95',
    contrast: 'De spreker selecteert niet bewust een dataset; hij behandelt een persoonlijk verhaal als algemeen bewijs.',
    optionIds: ['anecdotal-evidence', 'cherry-picking', 'hasty-generalization'],
  },
  {
    id: 'q-gambler-1',
    statement: 'De munt is vijf keer kop gevallen, dus nu moet het munt zijn.',
    correctFallacyId: 'gambler-fallacy',
    difficulty: 'Medium',
    category: 'Statistical fallacies',
    explanation: 'Bij een eerlijke munt blijft de kans per worp hetzelfde; eerdere worpen maken munt niet verschuldigd.',
    suspiciousPart: 'dus nu moet het munt zijn',
    contrast: 'Dit is geen valse oorzaak tussen twee verschillende gebeurtenissen; het is de aanname dat onafhankelijke kansen zichzelf direct compenseren.',
    optionIds: ['gambler-fallacy', 'false-cause', 'post-hoc'],
  },
  {
    id: 'q-no-true-1',
    statement: 'Geen echte natuurliefhebber rijdt ooit met de auto. Die persoon rijdt? Dan is hij geen echte natuurliefhebber.',
    correctFallacyId: 'no-true-scotsman',
    difficulty: 'Hard',
    category: 'Presumption',
    explanation: 'De definitie van natuurliefhebber wordt achteraf aangepast om een tegenvoorbeeld uit te sluiten.',
    suspiciousPart: 'Dan is hij geen echte natuurliefhebber.',
    contrast: 'Bij een gewone betekenisverschuiving verandert een woord binnen dezelfde redenering. Hier wordt vooral een groep opnieuw afgebakend na een tegenvoorbeeld.',
    optionIds: ['no-true-scotsman', 'equivocation', 'hasty-generalization'],
  },
  {
    id: 'q-guilt-1',
    statement: 'Die onderzoeker staat op dezelfde conferentie als complotdenkers, dus haar onderzoek deugt niet.',
    correctFallacyId: 'guilt-by-association',
    difficulty: 'Medium',
    category: 'Personal attacks',
    explanation: 'De inhoud van het onderzoek wordt niet besproken; alleen de verbinding met een groep wordt gebruikt om het af te wijzen.',
    suspiciousPart: 'staat op dezelfde conferentie als complotdenkers',
    contrast: 'Het is geen ad hominem op zichzelf, want er wordt geen persoonlijke eigenschap van de onderzoeker aangevallen. De associatie is de hele reden.',
    optionIds: ['guilt-by-association', 'ad-hominem', 'appeal-to-authority'],
  },
  {
    id: 'q-emotion-1',
    statement: 'Als je echt om je familie geeft, steun je dit plan.',
    correctFallacyId: 'appeal-to-emotion',
    difficulty: 'Easy',
    category: 'Emotional reasoning',
    explanation: 'Zorg voor de familie wordt gebruikt als drukmiddel in plaats van een inhoudelijk argument voor het plan.',
    suspiciousPart: 'Als je echt om je familie geeft',
    contrast: 'Er wordt geen concreet gevaar voorspeld, dus beroep op angst is te specifiek. De algemene emotionele druk is de juiste diagnose.',
    optionIds: ['appeal-to-emotion', 'appeal-to-fear', 'false-dilemma'],
  },
  {
    id: 'q-popularity-1',
    statement: 'Miljoenen mensen gebruiken dit dieet, dus het moet gezond zijn.',
    correctFallacyId: 'appeal-to-popularity',
    difficulty: 'Easy',
    category: 'Emotional reasoning',
    explanation: 'Veel gebruikers maken een dieet niet automatisch gezond.',
    suspiciousPart: 'Miljoenen mensen gebruiken dit dieet',
    contrast: 'Er wordt geen specifieke expert opgevoerd. Het bewijs is het aantal mensen, niet de status van een autoriteit.',
    optionIds: ['appeal-to-popularity', 'appeal-to-authority', 'anecdotal-evidence'],
  },
  {
    id: 'q-composition-1',
    statement: 'Elke speler van dit team is uitstekend, dus het team zal zeker uitstekend samenwerken.',
    correctFallacyId: 'composition-fallacy',
    difficulty: 'Hard',
    category: 'Ambiguity',
    explanation: 'Individuele kwaliteit garandeert niet dat spelers goed samenwerken als geheel.',
    suspiciousPart: 'dus het team zal zeker uitstekend samenwerken',
    contrast: 'Er is geen onduidelijk woord zoals bij equivocation. De fout is dat een eigenschap van elk onderdeel naar het geheel wordt gekopieerd.',
    optionIds: ['composition-fallacy', 'equivocation', 'hasty-generalization'],
  },
  {
    id: 'q-survivorship-1',
    statement: 'Alle succesvolle ondernemers begonnen zonder plan, dus een plan hebben is onnodig.',
    correctFallacyId: 'survivorship-bias',
    difficulty: 'Hard',
    category: 'Statistical fallacies',
    explanation: 'De ondernemers die zonder plan mislukten zijn niet meegenomen in de conclusie.',
    suspiciousPart: 'Alle succesvolle ondernemers begonnen zonder plan',
    contrast: 'Dit is meer dan een paar persoonlijke voorbeelden: de selectie bestaat uit zichtbare winnaars terwijl de uitvallers ontbreken.',
    optionIds: ['survivorship-bias', 'cherry-picking', 'anecdotal-evidence'],
  },
  {
    id: 'q-red-herring-2',
    statement: 'Waarom heb je mijn bericht niet beantwoord? We hebben toch een leuke vakantie gehad?',
    correctFallacyId: 'red-herring',
    difficulty: 'Medium',
    category: 'Relevance',
    explanation: 'Een leuke vakantie beantwoordt niet waarom het bericht onbeantwoord bleef.',
    suspiciousPart: 'We hebben toch een leuke vakantie gehad?',
    contrast: 'Het vakantiefeit is geen tegenargument en verdraait niets; het leidt de aandacht alleen af van de vraag.',
    optionIds: ['red-herring', 'appeal-to-emotion', 'strawman'],
  },
  {
    id: 'q-no-fallacy-2',
    statement: 'De testgroep scoorde gemiddeld hoger nadat de nieuwe oefenmethode vier weken was gebruikt, maar we vergelijken ook met een controlegroep.',
    correctFallacyId: null,
    difficulty: 'Medium',
    category: null,
    explanation: 'Dit is zorgvuldig geformuleerd bewijs: de spreker noemt de uitkomst en een controlegroep die alternatieve verklaringen helpt toetsen.',
    suspiciousPart: 'maar we vergelijken ook met een controlegroep',
    contrast: 'Er wordt juist niet zomaar causaliteit geclaimd. De extra vergelijking maakt de conclusie sterker, zonder te doen alsof al het bewijs absoluut is.',
    optionIds: ['false-cause', 'correlation-causation', 'cherry-picking'],
  },
  {
    id: 'q-fear-1',
    statement: 'Als we deze beveiligingsdienst niet nemen, worden we binnen een maand zeker gehackt.',
    correctFallacyId: 'appeal-to-fear',
    difficulty: 'Easy',
    category: 'Emotional reasoning',
    explanation: 'Een angstscenario wordt als zekerheid gebruikt om een aankoop af te dwingen.',
    suspiciousPart: 'worden we binnen een maand zeker gehackt',
    contrast: 'Er wordt geen hele reeks tussenstappen uitgewerkt. De druk komt direct uit het dreigende scenario, dus beroep op angst past beter dan glijdende schaal.',
    optionIds: ['appeal-to-fear', 'slippery-slope', 'appeal-to-emotion'],
  },
  {
    id: 'q-hard-cause-1',
    statement: 'De verkoop steeg nadat de nieuwe kleur werd gelanceerd, dus alleen de kleur veroorzaakte de groei.',
    correctFallacyId: 'false-cause',
    difficulty: 'Hard',
    category: 'Causation',
    explanation: 'Er kunnen tegelijk reclame, seizoen, prijs of andere veranderingen zijn geweest. De conclusie wijst zonder controle een enkele oorzaak aan.',
    suspiciousPart: 'dus alleen de kleur veroorzaakte de groei',
    contrast: 'Er is geen onafhankelijke kansreeks zoals bij de gokkersmisvatting en ook geen vergelijking tussen variabelen; dit is een onbewezen enkelvoudige oorzaak.',
    optionIds: ['false-cause', 'correlation-causation', 'post-hoc'],
  },
  {
    id: 'q-hard-generalization-1',
    statement: 'In onze beste klantcases werkte coaching goed. Coaching werkt dus voor elk bedrijf.',
    correctFallacyId: 'cherry-picking',
    difficulty: 'Hard',
    category: 'Statistical fallacies',
    explanation: 'Alleen succesvolle cases worden gebruikt; bedrijven waar coaching niet werkte blijven onzichtbaar.',
    suspiciousPart: 'In onze beste klantcases werkte coaching goed.',
    contrast: 'De fout zit niet alleen in de brede conclusie, maar in het bewust kiezen van de beste cases voordat de conclusie wordt getrokken.',
    optionIds: ['cherry-picking', 'hasty-generalization', 'survivorship-bias'],
  },
  {
    id: 'q-authority-2',
    statement: 'De bekendste econoom van het land voorspelt een recessie, dus er komt zeker een recessie.',
    correctFallacyId: 'appeal-to-authority',
    difficulty: 'Hard',
    category: 'Relevance',
    explanation: 'Zelfs een relevante expert kan een voorspelling verkeerd hebben. De autoriteit maakt de uitkomst niet zeker.',
    suspiciousPart: 'dus er komt zeker een recessie',
    contrast: 'Dit zou geen drogreden zijn als de voorspelling naast andere economische data wordt beoordeeld. Hier is de status van de econoom het enige bewijs.',
    optionIds: ['appeal-to-authority', 'appeal-to-popularity', 'false-cause'],
  },
  {
    id: 'q-no-fallacy-3',
    statement: 'Ik ben het niet eens met je conclusie, maar je bron bevat wel een controleerbare dataset die jouw punt ondersteunt.',
    correctFallacyId: null,
    difficulty: 'Hard',
    category: null,
    explanation: 'Een bron of dataset beoordelen is geen beroep op autoriteit zolang de inhoud controleerbaar wordt besproken.',
    suspiciousPart: 'je bron bevat wel een controleerbare dataset',
    contrast: 'Er wordt niet gezegd dat de bron gelijk heeft omdat hij beroemd is; de data zelf zijn het onderwerp van beoordeling.',
    optionIds: ['appeal-to-authority', 'red-herring', 'cherry-picking'],
  },
]

export const fallacyById = Object.fromEntries(fallacies.map((fallacy) => [fallacy.id, fallacy])) as Record<string, Fallacy>
