import type { CourseModule, CourseStage, Lesson, SkillId } from '../domain/course-types'
import { expandedLessons, expandedModules, expandedStages, stageModuleAdditions } from './catalog/expanded-catalog'

const lesson = (
  id: string, moduleId: string, title: string, subtitle: string, skills: SkillId[],
  challenge: string, explanation: string[], example: string, exerciseId?: string,
  resourceIds: string[] = ['python-tutorial'], kind: Lesson['kind'] = 'challenge', difficulty: Lesson['difficulty'] = 3,
): Lesson => ({
  id, moduleId, title, subtitle, kind, minutes: kind === 'math-lab' ? 30 : 20, difficulty,
  objectives: [`Explain ${title.toLowerCase()} in your own words.`, `Apply it without copying a finished solution.`, 'Recognize one common mistake and test the edge case that exposes it.'],
  explanation, example, challenge, exerciseId, resourceIds, skillIds: skills,
})

const originalStages: CourseStage[] = [
  { id: 'stage-0', order: 0, title: 'Re-entry & Diagnostic Repair', description: 'Restore the Python mental models that faded during your break and repair the exact gaps found in your diagnostic.', moduleIds: ['m0-tracing','m0-functions','m0-diagnostic'], accent: '#65d29a' },
  { id: 'stage-1', order: 1, title: 'Reliable Python', description: 'Become comfortable with nested data, sorting, validation, classes, JSON, and tests.', moduleIds: ['m1-data','m1-errors','m1-quality'], accent: '#45b97c' },
  { id: 'stage-2', order: 2, title: 'Algorithms & Data Structures', description: 'Learn to choose structures, reason about runtime, and solve route and search problems.', moduleIds: ['m2-complexity','m2-structures','m2-graphs'], accent: '#3987e5' },
  { id: 'stage-3', order: 3, title: 'APIs & Responsible Scraping', description: 'Collect web data reliably while respecting rate limits, terms, privacy, and security boundaries.', moduleIds: ['m3-http','m3-html','m3-pipeline'], accent: '#d95926' },
  { id: 'stage-4', order: 4, title: 'Data, Statistics & Visualization', description: 'Turn raw records into trustworthy analysis and honest visual explanations.', moduleIds: ['m4-arrays','m4-statistics','m4-visuals'], accent: '#c98500' },
  { id: 'stage-5', order: 5, title: 'Machine Learning', description: 'Build models that beat baselines, avoid leakage, and explain their errors.', moduleIds: ['m5-foundations','m5-models','m5-evaluation'], accent: '#d55181' },
  { id: 'stage-6', order: 6, title: 'Neural Networks', description: 'Learn the mathematics and code behind neurons, gradients, dense networks, and image inputs.', moduleIds: ['m6-linear','m6-gradients','m6-networks'], accent: '#9085e9' },
  { id: 'stage-7', order: 7, title: 'Capstone Lab', description: 'Combine the full path in ambitious projects: sports prediction, recommenders, useful tools, and Flappy Bird AI.', moduleIds: ['m7-recommender','m7-flappy','m7-professional'], accent: '#e66767' },
]

export const stages: CourseStage[] = [
  ...originalStages.map((stage) => ({ ...stage, assessmentId: `readiness-${stage.id}`, moduleIds: [...stage.moduleIds, ...(stageModuleAdditions[stage.id] ?? [])] })),
  ...expandedStages.map((stage) => ({ ...stage, assessmentId: `readiness-${stage.id}` })),
]

export const lessons: Lesson[] = [
  lesson('trace-values','m0-tracing','Trace values and identity','Predict code instead of guessing from familiar words.',['syntax'], 'Explain why two names can point at the same list and why `is` is not a variable.', ['Assignment gives a name a reference to an object.', '`is` compares identity; `==` compares value.', 'Mutating a shared list is visible through every name pointing at it.'], "numbers = [1, 2, 3]\nother = numbers\nother.append(4)\n# numbers is now [1, 2, 3, 4]"),
  lesson('truthiness-slices','m0-tracing','Truthiness and slices','Make conditions and slicing rules predictable.',['syntax','strings'], 'Predict which values survive an `if value` test and calculate three slices by index.', ['Empty containers, zero, empty strings, and None are falsy.', 'A slice excludes its stop index.', 'A negative step walks backward.'], "text = 'personalized'\ntext[1:8:2]  # 'esnl'\ntext[-4:]    # 'ized'", 'count-truthy'),
  lesson('function-contracts','m0-functions','Function contracts','Define what valid input, output, and failure mean.',['functions','exceptions'], 'Write a clamp function and choose a clear behavior for reversed limits.', ['A function contract describes accepted input, returned output, and raised errors.', 'Returning an error string mixes valid results with failures.', 'Raise a specific exception when the caller broke the contract.'], "def clamp(value, minimum, maximum):\n    if minimum > maximum:\n        raise ValueError('minimum exceeds maximum')", 'describe-number'),
  lesson('range-primes','m0-functions','Ranges and efficient primes','Fix inclusive endpoints and stop unnecessary work.',['loops','functions','complexity'], 'Repair find_primes so a prime at end is included, then explain the square-root stopping rule.', ['The stop of range is exclusive.', 'A composite number has at least one factor no larger than its square root.', 'Use a helper to keep primality logic in one place.'], 'for number in range(start, end + 1):\n    if is_prime(number): ...', 'inclusive-primes'),
  lesson('pure-counting','m0-diagnostic','Pure counting functions','Remove accidental output and separate transformation steps.',['strings','dictionaries'], 'Refactor the diagnostic word counter so it returns data without printing during the loop.', ['A pure transformation returns its result without unrelated side effects.', 'Dictionary get removes a repeated membership branch.', 'Tiny intermediate names make a pipeline easier to debug.'], "counts[word] = counts.get(word, 0) + 1", 'normalize-name'),
  lesson('ranking-repair','m0-diagnostic','Sorting and diagnostic repair','Complete top_words with deterministic tie handling.',['sorting','dictionaries','exceptions'], 'Finish the exact task that stopped the diagnostic and explain each part of the sorting key.', ['Dictionary items produce word/count pairs.', 'Negative count sorts larger counts first.', 'The word as a second key makes ties stable and testable.'], "sorted(counts.items(), key=lambda item: (-item[1], item[0]))", 'top-words', ['python-sorting','pytest-docs'], 'review', 4),

  lesson('collections-choice','m1-data','Choose the right collection','Use lists, tuples, sets, and dictionaries for different jobs.',['dictionaries','nested-data'], 'Select a data structure for order, uniqueness, lookup, and fixed records.', ['Lists preserve ordered sequences.', 'Sets enforce uniqueness and fast membership.', 'Dictionaries associate keys with values; tuples represent fixed ordered records.'], "paying_customers = set()\nrevenue_by_customer = {}"),
  lesson('nested-aggregation','m1-data','Aggregate nested records','Turn rows into totals and rankings in one pass.',['dictionaries','nested-data','sorting'], 'Summarize paid and unpaid orders without modifying the input.', ['Inspect one record at a time.', 'Maintain small accumulators for each requested result.', 'Finish by converting sets and ranking dictionaries.'], "totals[name] = totals.get(name, 0) + price", 'summarize-orders'),
  lesson('raise-or-propagate','m1-errors','Raise, catch, or propagate','Make error boundaries intentional.',['exceptions'], 'Decide which layer should catch malformed user input and which should let programmer errors surface.', ['Raise when your function detects a broken contract.', 'Catch only when you can recover or add useful context.', 'Propagation lets a caller choose the policy.'], "try:\n    score = int(raw)\nexcept ValueError as error:\n    raise ValueError('score must be an integer') from error", 'safe-average'),
  lesson('json-validation','m1-errors','JSON and validation','Separate parsing from shape validation.',['exceptions','nested-data'], 'Parse a score report and reject empty or malformed student records.', ['Valid JSON can still contain invalid application data.', 'Validate required keys and types before calculating.', 'Context managers guarantee file closure in local projects.'], "with open(path, encoding='utf-8') as handle:\n    students = json.load(handle)", 'parse-score-report'),
  lesson('objects-state','m1-quality','Objects and state','Use a class when behavior protects changing state.',['oop','exceptions'], 'Model an account that cannot withdraw money it does not have.', ['An instance owns state; methods enforce its rules.', 'self refers to the current instance.', 'Private-by-convention attributes reduce accidental mutation but do not create absolute secrecy.'], 'account.deposit(50)\naccount.withdraw(30)', 'bank-account'),
  lesson('tests-as-reasons','m1-quality','Tests as reasons','Write tests that explain why behavior matters.',['testing'], 'Design six tests for average_positive and name the regression each prevents.', ['Examples cover the common path.', 'Boundaries expose zero, empty input, and invalid values.', 'A good test name explains the business rule, not merely the function call.'], "def test_zero_is_not_positive():\n    with pytest.raises(ValueError):\n        average_positive([0])", 'safe-average', ['pytest-docs'], 'review'),

  lesson('big-o-intuition','m2-complexity','Big-O intuition','Compare how work grows as input grows.',['complexity','algorithms'], 'Rank constant, logarithmic, linear, n log n, and quadratic growth with concrete input sizes.', ['Big-O describes growth, not exact seconds.', 'Constants matter in practice but do not change the growth class.', 'Choose an algorithm only after understanding input shape and constraints.'], 'Binary search halves the remaining candidates: O(log n).', undefined, ['big-o','visualgo'], 'concept'),
  lesson('binary-search-lesson','m2-complexity','Binary search','Maintain a shrinking invariant in sorted data.',['algorithms','complexity'], 'Find a target without scanning every item.', ['Binary search requires sorted input.', 'Every step preserves the promise that a target can only be inside low..high.', 'Moving past middle prevents infinite loops.'], 'middle = (low + high) // 2', 'binary-search', ['visualgo']),
  lesson('stacks-queues','m2-structures','Stacks and queues','Match data access order to the problem.',['algorithms'], 'Explain why bracket matching is LIFO and BFS is FIFO.', ['Stacks remove the most recent item.', 'Queues remove the oldest waiting item.', 'The access pattern often reveals the correct structure.'], 'stack.append(opening)\nlatest = stack.pop()', 'valid-brackets', ['visualgo']),
  lesson('recursion-dp','m2-structures','Recursion and dynamic programming','Turn repeated subproblems into stored answers.',['algorithms','complexity'], 'Trace a recursive Fibonacci call tree, then remove duplicate work.', ['Recursion needs a base case and progress toward it.', 'Memoization caches results of repeated states.', 'Bottom-up dynamic programming builds answers in dependency order.'], "cache = {0: 0, 1: 1}\nfor n in range(2, target + 1): ...", undefined, ['visualgo'], 'concept', 4),
  lesson('graphs-bfs','m2-graphs','Graphs and breadth-first search','Represent connections and find shortest unweighted routes.',['algorithms','nested-data','complexity'], 'Find the shortest route through a small sports venue or game map.', ['An adjacency dictionary maps a node to its neighbors.', 'BFS explores by distance layers.', 'Mark nodes when queued to avoid duplicate work.'], "graph = {'A': ['B', 'C'], 'B': ['D'], 'C': ['D']}", 'bfs-path', ['visualgo'], 'challenge', 4),
  lesson('algorithm-comparison','m2-graphs','Compare algorithms honestly','Measure behavior and explain trade-offs.',['algorithms','complexity','testing'], 'Solve one search problem linearly and with binary search, then state when each is valid.', ['A faster complexity class can require stronger preconditions.', 'Benchmarks need representative data and repeated runs.', 'Correctness comes before optimization.'], 'Linear search works on unsorted data; binary search needs sorted data.', undefined, ['big-o'], 'review', 4),

  lesson('http-model','m3-http','HTTP and JSON','Understand request, response, status, headers, and body.',['apis','nested-data'], 'Inspect a fixture response and extract names without assuming every request succeeded.', ['A status code summarizes the outcome.', 'JSON gives syntax, not trustworthy schema.', 'APIs often paginate large collections.'], "response = {'status': 200, 'data': {'items': [...]}}", 'parse-api-page', ['requests']),
  lesson('pagination-retries','m3-http','Pagination and retries','Continue safely without retrying every failure.',['apis','exceptions','security'], 'Design deterministic rules for next pages, timeouts, 429, and permanent 4xx failures.', ['Follow explicit next-page metadata.', 'Retry temporary failures with bounded backoff.', 'Do not retry invalid authentication or malformed requests forever.'], 'Retry 429/503 with a cap; fail loudly on 400/401/403.', undefined, ['requests'], 'concept'),
  lesson('html-parsing','m3-html','Parse HTML structurally','Use a parser instead of fragile string slicing.',['scraping','strings'], 'Extract safe links from an HTML fixture while preserving first-seen order.', ['HTML is a tree-like document, not reliable plain text.', 'Selectors or parser callbacks target structure.', 'Normalize and deduplicate after extraction.'], '<a href="https://example.com">Example</a>', 'extract-links', ['beautifulsoup']),
  lesson('scraping-ethics','m3-html','Responsible scraping','Decide whether and how collection should happen.',['scraping','security'], 'Create a preflight checklist covering API preference, robots, terms, privacy, rate, and caching.', ['Prefer an official API when available.', 'robots.txt is operational guidance, not the only legal or ethical question.', 'Collect the minimum data needed and identify yourself when appropriate.'], 'Check permission → rate limit → cache → log → stop on errors.', undefined, ['robots','beautifulsoup'], 'concept'),
  lesson('clean-pipeline','m3-pipeline','Clean an extraction pipeline','Convert inconsistent records into a stable data contract.',['scraping','data-analysis','exceptions'], 'Normalize names, parse scores, skip malformed rows, and remove duplicates.', ['Keep raw capture separate from cleaned output.', 'Record skipped-row counts in real projects.', 'Deterministic cleaning makes later analysis reproducible.'], "{'team': ' ajax ', 'score': '3'} → {'team': 'Ajax', 'score': 3}", 'clean-records'),
  lesson('collector-design','m3-pipeline','Design a resilient collector','Combine pagination, rate limits, validation, and persistence.',['apis','scraping','security','testing'], 'Sketch a collector that can resume after failure without duplicating records.', ['Separate fetch, parse, validate, and save steps.', 'Persist checkpoints only after validated pages.', 'Use fixtures for tests so CI never depends on a live site.'], 'fetch_page → validate → clean → save → checkpoint', undefined, ['requests','robots'], 'project-step', 5),

  lesson('arrays-vectors','m4-arrays','Arrays and vector thinking','Replace item-by-item Python loops when data has a regular numeric shape.',['data-analysis','linear-algebra'], 'Translate three scalar calculations into vector operations and explain the shape.', ['A vector is an ordered collection of numbers.', 'Array shapes make dimensions explicit.', 'Vectorized operations express the mathematical intention directly.'], 'scores = [1, 2, 3, 4, 5]\n# a moving window summarizes local form', 'moving-average', ['numpy']),
  lesson('pandas-cleaning','m4-arrays','Tables and cleaning','Select, group, join, and validate tabular data.',['data-analysis','nested-data'], 'Plan a pandas pipeline for match data with missing scores and duplicate IDs.', ['Rows are observations and columns are variables.', 'Inspect types and missingness before modeling.', 'Keep a raw snapshot and a reproducible cleaning function.'], "matches.drop_duplicates('match_id').dropna(subset=['home_score'])", undefined, ['pandas'], 'concept'),
  lesson('summary-statistics','m4-statistics','Mean, spread, and z-scores','Describe both center and variation.',['statistics','data-analysis'], 'Standardize values and explain what -1, 0, and +1 mean.', ['The mean summarizes center but can hide shape.', 'Variance averages squared distance from the mean.', 'A z-score expresses distance in standard-deviation units.'], 'z = (value - mean) / standard_deviation', 'standardize', ['statquest'], 'math-lab', 4),
  lesson('probability-sampling','m4-statistics','Probability and sampling','Reason about uncertainty without pretending samples are certainty.',['statistics'], 'Simulate repeated samples and explain why their averages vary.', ['Probability models uncertainty over repeated possibilities.', 'A sample can differ from the population by chance.', 'Selection bias is not repaired by a large sample.'], 'A fair coin model predicts a distribution, not an exact short sequence.', undefined, ['statquest'], 'math-lab', 4),
  lesson('chart-choice','m4-visuals','Choose an honest chart','Match visual form to comparison, trend, distribution, or relationship.',['data-analysis','statistics'], 'Choose forms for weekly minutes, skill mastery, result distribution, and model errors.', ['Single values are stat tiles, not one-bar charts.', 'Time trends usually use lines.', 'Magnitude comparisons usually use bars; distributions need histograms or box plots.'], 'Weekly minutes → line; skill mastery → horizontal bars.', undefined, ['pandas'], 'concept'),
  lesson('data-story','m4-visuals','Tell a data story with limits','State what the data supports and what remains uncertain.',['data-analysis','statistics'], 'Write a five-sentence conclusion from a sports chart including one limitation.', ['Lead with the decision-relevant finding.', 'Quantify the evidence.', 'Name uncertainty, missing data, or confounding factors.'], 'Finding → evidence → comparison → limitation → next check.', undefined, ['statquest'], 'review'),

  lesson('features-targets','m5-foundations','Features, targets, and splits','Define what the model knows and what it predicts.',['machine-learning','data-analysis'], 'Design a sports prediction table that contains no future information.', ['Features are inputs available at prediction time.', 'The target is the outcome to learn.', 'Chronological problems require time-aware splitting.'], 'Past form can be a feature; final score cannot be a pre-match feature.', 'chronological-split', ['kaggle-ml']),
  lesson('baselines','m5-foundations','Baselines before models','Prove the model adds value beyond a simple rule.',['machine-learning','statistics'], 'Build a majority-class baseline and state what beating it means.', ['A baseline anchors evaluation.', 'A complex model below baseline is not useful.', 'Use the same split and metric for fair comparison.'], 'Predict the most common training result for every test match.', 'majority-baseline', ['kaggle-ml']),
  lesson('regression-classification','m5-models','Regression and classification','Match model output to the question.',['machine-learning','statistics'], 'Choose regression or classification for score, win probability, and league position.', ['Regression predicts numeric quantities.', 'Classification predicts categories or class probabilities.', 'The framing determines metrics and errors.'], 'Goals scored → regression; win/draw/loss → multiclass classification.', undefined, ['sklearn','statquest'], 'concept'),
  lesson('trees-forests','m5-models','Trees and random forests','Learn nonlinear rules while controlling overfitting.',['machine-learning','algorithms'], 'Trace a small decision tree and explain why a forest is less fragile.', ['A tree splits data with simple questions.', 'Deep trees can memorize training noise.', 'Forests average diverse trees to reduce variance.'], 'if recent_form > 0.7 and opponent_rank > 10: ...', undefined, ['sklearn','statquest'], 'concept', 4),
  lesson('metrics-errors','m5-evaluation','Metrics and confusion matrices','Choose a metric that matches the cost of mistakes.',['machine-learning','statistics','dictionaries'], 'Calculate accuracy, precision, recall, and confusion counts.', ['Accuracy can hide minority-class failure.', 'Precision asks how often positive predictions are correct.', 'Recall asks how many actual positives were found.'], 'tp, tn, fp, fn form the confusion matrix.', 'classification-metrics', ['statquest']),
  lesson('leakage-crossvalidation','m5-evaluation','Leakage, validation, and interpretation','Build trustworthy experiments rather than impressive-looking scores.',['machine-learning','testing','statistics'], 'Identify leakage in five sports features and design a time-aware validation plan.', ['Leakage gives the model information unavailable in reality.', 'Cross-validation estimates variation across splits.', 'Interpretation checks what the model actually used.'], 'A post-match rating is leakage for a pre-match predictor.', undefined, ['sklearn','kaggle-ml'], 'review', 5),

  lesson('vectors-matrices','m6-linear','Vectors and matrices','See data and transformations as shapes.',['linear-algebra','neural-networks'], 'Compute a dot product and draw its geometric interpretation.', ['Vectors can represent features, directions, or points.', 'Matrices transform or combine vectors.', 'The dot product measures weighted combination and alignment.'], '[1,2,3] · [4,5,6] = 32', 'dot-product', ['3b1b-linear'], 'math-lab', 4),
  lesson('matrix-shapes','m6-linear','Matrix shapes and batches','Track dimensions before writing neural-network code.',['linear-algebra','neural-networks'], 'Label the shapes of a batch, weight matrix, bias vector, and output.', ['A batch stacks examples in rows.', 'Weights connect every input feature to every output unit.', 'Shape errors are often clearer than value errors.'], '(batch, inputs) @ (inputs, outputs) → (batch, outputs)', undefined, ['3b1b-linear'], 'math-lab', 4),
  lesson('derivatives-gradients','m6-gradients','Derivatives and gradients','Interpret slope as a direction for reducing loss.',['linear-algebra','neural-networks','statistics'], 'Estimate a derivative numerically, then update parameters opposite the gradient.', ['A derivative measures local sensitivity.', 'A gradient contains one derivative per parameter.', 'Learning rate controls step size.'], 'new_parameter = parameter - learning_rate * gradient', 'gradient-step', ['3b1b-calculus','3b1b-neural'], 'math-lab', 5),
  lesson('loss-optimization','m6-gradients','Loss and optimization','Connect prediction error to parameter updates.',['neural-networks','statistics'], 'Compare squared error and cross-entropy conceptually, then diagnose a learning rate that is too high.', ['Loss converts model mistakes into a number to minimize.', 'Optimization uses gradients, but progress is not guaranteed with a bad rate.', 'Training and validation loss answer different questions.'], 'Oscillating loss can mean the learning rate is too large.', undefined, ['3b1b-neural','statquest'], 'concept', 5),
  lesson('dense-neurons','m6-networks','Dense neurons and activations','Build a neuron from weighted sums, bias, and ReLU.',['neural-networks','linear-algebra'], 'Implement one neuron and trace how each input changes its output.', ['Weights control input influence.', 'Bias shifts the activation threshold.', 'ReLU keeps positive values and clips negative ones to zero.'], 'relu(dot(inputs, weights) + bias)', 'dense-neuron', ['3b1b-neural']),
  lesson('backprop-images','m6-networks','Backpropagation and images','Understand credit assignment and image tensors.',['neural-networks','linear-algebra'], 'Trace one forward/backward pass and explain why image shape matters.', ['Backpropagation applies the chain rule from loss back to parameters.', 'Images are numeric tensors with height, width, and channels.', 'Evaluation needs per-class errors, not only one accuracy number.'], '(height, width, channels) → flattened features or convolutional layers', undefined, ['3b1b-neural','kaggle-deep'], 'review', 5),

  lesson('recommender-baseline','m7-recommender','Recommendation baselines','Start with popularity before similarity.',['machine-learning','algorithms'], 'Rank unseen items with deterministic tie-breaking.', ['Recommendation begins with candidate generation.', 'A popularity baseline is easy to explain and hard to beat for sparse users.', 'Never recommend already consumed items unless repetition is intentional.'], 'filter seen → score candidates → sort → limit', 'recommend-items', ['sklearn']),
  lesson('similarity-evaluation','m7-recommender','Similarity and offline evaluation','Measure whether personalized ranking improves held-out choices.',['machine-learning','statistics','linear-algebra'], 'Design a train/test split for user interactions and choose precision@k.', ['Similarity can compare users or items.', 'Hold out later interactions to simulate future recommendations.', 'Explainability can show shared attributes or similar past choices.'], 'precision@k = relevant recommendations / k', undefined, ['statquest'], 'project-step', 5),
  lesson('fitness-design','m7-flappy','Fitness function design','Turn game behavior into a learnable objective.',['machine-learning','algorithms'], 'Balance survival, pipe progress, and gap alignment without rewarding useless stalling.', ['Agents optimize exactly what the score rewards.', 'Shaping rewards can speed learning but introduce loopholes.', 'Evaluate on multiple seeds and unseen scenarios.'], 'survival + progress reward - distance penalty', 'flappy-fitness', ['pygame'], 'project-step', 5),
  lesson('neat-workflow','m7-flappy','NEAT training workflow','Evolve network structure and weights in a local game environment.',['machine-learning','neural-networks'], 'Plan population, state inputs, outputs, fitness, checkpoints, and evaluation.', ['NEAT evolves both topology and weights.', 'Training logs should record generation-level progress.', 'A trained agent needs evaluation separate from its training seed.'], 'state → network → flap decision → environment → fitness', undefined, ['pygame'], 'project-step', 5),
  lesson('maintainable-project','m7-professional','Build maintainable Python','Separate domain logic, I/O, configuration, and tests.',['testing','functions','oop'], 'Design the folder structure for a sports predictor or Magis Data tool.', ['Pure domain functions are easiest to test.', 'I/O belongs at boundaries.', 'Configuration and secrets stay outside source code.'], 'src/project/domain.py\nsrc/project/io.py\ntests/test_domain.py', undefined, ['pytest-docs'], 'project-step', 4),
  lesson('capstone-release','m7-professional','Release your capstone','Verify, document, demo, and reflect like a professional developer.',['testing','security','machine-learning'], 'Prepare a final checklist covering setup, tests, data ethics, model limits, screenshots, and next improvements.', ['A README is part of the product.', 'Reproducibility requires pinned dependencies and clear commands.', 'A useful demo states limitations rather than hiding them.'], 'install → run → test → reproduce result → explain limitation', undefined, ['pytest-docs','sklearn'], 'review', 5),
  ...expandedLessons,
]

const module = (id: string, stageId: string, title: string, description: string, prerequisiteIds: string[], lessonIds: string[], bossChallenge: string, projectId: string): CourseModule => ({ id, stageId, title, description, prerequisiteIds, lessonIds, bossChallenge, projectId })

export const modules: CourseModule[] = [
  module('m0-tracing','stage-0','Mental models','Identity, truthiness, slicing, and code tracing.',[],['trace-values','truthiness-slices'],'Predict eight short snippets and explain every result.','word-insight'),
  module('m0-functions','stage-0','Functions that keep promises','Contracts, exceptions, ranges, and reusable helpers.',[],['function-contracts','range-primes'],'Repair a collection of functions with hidden boundary failures.','word-insight'),
  module('m0-diagnostic','stage-0','Diagnostic repair','Turn the unfinished word counter into tested, ranked output.',['m0-tracing','m0-functions'],['pure-counting','ranking-repair'],'Complete top_words independently after a delayed retry.','word-insight'),
  module('m1-data','stage-1','Data structures and aggregation','Choose structures and combine nested records.',['m0-diagnostic'],['collections-choice','nested-aggregation'],'Build a league table from raw matches.','sports-table'),
  module('m1-errors','stage-1','Validation and files','Make malformed input fail clearly.',['m1-data'],['raise-or-propagate','json-validation'],'Load and validate a season file with a useful error report.','sports-table'),
  module('m1-quality','stage-1','Objects and tests','Protect state and prove business rules.',['m1-errors'],['objects-state','tests-as-reasons'],'Ship a tested tournament tracker.','sports-table'),
  module('m2-complexity','stage-2','Complexity and search','Understand growth and logarithmic search.',['m1-quality'],['big-o-intuition','binary-search-lesson'],'Choose and justify a search strategy for three datasets.','route-finder'),
  module('m2-structures','stage-2','Stacks, queues, recursion','Use access patterns and stored subproblems.',['m2-complexity'],['stacks-queues','recursion-dp'],'Solve bracket validation and one memoized puzzle.','route-finder'),
  module('m2-graphs','stage-2','Graphs and routes','Represent networks and compare traversals.',['m2-structures'],['graphs-bfs','algorithm-comparison'],'Find and explain the shortest route through a graph.','route-finder'),
  module('m3-http','stage-3','HTTP and APIs','Parse responses, paginate, and retry selectively.',['m1-errors'],['http-model','pagination-retries'],'Consume a paginated fixture API without duplicate records.','sports-collector'),
  module('m3-html','stage-3','HTML and ethics','Parse structure and decide whether collection is appropriate.',['m3-http'],['html-parsing','scraping-ethics'],'Extract data only after passing a scraping preflight.','sports-collector'),
  module('m3-pipeline','stage-3','Reliable collectors','Clean, checkpoint, and test collection pipelines.',['m3-html'],['clean-pipeline','collector-design'],'Build a resumable fixture-based sports collector.','sports-collector'),
  module('m4-arrays','stage-4','Arrays and tables','Use numeric shapes and reproducible cleaning.',['m1-data'],['arrays-vectors','pandas-cleaning'],'Clean and summarize a season dataset.','sports-dashboard'),
  module('m4-statistics','stage-4','Statistics and uncertainty','Measure center, spread, probability, and sampling variation.',['m4-arrays'],['summary-statistics','probability-sampling'],'Explain a surprising sports statistic without overstating certainty.','sports-dashboard'),
  module('m4-visuals','stage-4','Honest visualization','Choose forms and communicate limitations.',['m4-statistics'],['chart-choice','data-story'],'Create a dashboard with a written evidence-based conclusion.','sports-dashboard'),
  module('m5-foundations','stage-5','ML foundations','Define prediction data, splits, and baselines.',['m4-statistics'],['features-targets','baselines'],'Design a leakage-free sports prediction dataset.','sports-predictor'),
  module('m5-models','stage-5','Model families','Choose regression, classification, trees, and forests.',['m5-foundations'],['regression-classification','trees-forests'],'Train and compare two model families locally.','sports-predictor'),
  module('m5-evaluation','stage-5','Evaluation and trust','Use metrics, validation, interpretation, and leakage checks.',['m5-models'],['metrics-errors','leakage-crossvalidation'],'Prove whether a model beats baseline and where it fails.','sports-predictor'),
  module('m6-linear','stage-6','Linear algebra','Build vector, matrix, and shape intuition.',['m4-statistics'],['vectors-matrices','matrix-shapes'],'Calculate a small dense layer by hand and in Python.','neural-from-scratch'),
  module('m6-gradients','stage-6','Calculus for learning','Connect derivatives, loss, and parameter updates.',['m6-linear'],['derivatives-gradients','loss-optimization'],'Optimize a two-parameter function and plot its loss.','neural-from-scratch'),
  module('m6-networks','stage-6','Neural networks','Combine neurons, activations, backpropagation, and image shapes.',['m6-gradients'],['dense-neurons','backprop-images'],'Train a small NumPy network and analyze errors.','neural-from-scratch'),
  module('m7-recommender','stage-7','Recommendation systems','Rank candidates and evaluate personalized results.',['m5-evaluation'],['recommender-baseline','similarity-evaluation'],'Ship an explainable recommender with a baseline.','recommender'),
  module('m7-flappy','stage-7','Game-playing AI','Design state, fitness, training, and evaluation.',['m6-networks'],['fitness-design','neat-workflow'],'Train a local Flappy Bird agent and evaluate unseen runs.','flappy-ai'),
  module('m7-professional','stage-7','Professional delivery','Structure, test, document, and release a capstone.',['m5-evaluation'],['maintainable-project','capstone-release'],'Release one polished capstone with reproducible setup.','magis-tool'),
  ...expandedModules,
]

export const stageById = Object.fromEntries(stages.map((stage) => [stage.id, stage]))
export const moduleById = Object.fromEntries(modules.map((item) => [item.id, item]))
export const lessonById = Object.fromEntries(lessons.map((item) => [item.id, item]))

export function validateCatalog() {
  const ids = [...stages.map((x) => x.id), ...modules.map((x) => x.id), ...lessons.map((x) => x.id)]
  if (new Set(ids).size !== ids.length) throw new Error('Course catalog contains duplicate IDs')
  for (const stage of stages) for (const id of stage.moduleIds) if (!moduleById[id]) throw new Error(`Missing module ${id}`)
  for (const item of modules) {
    for (const id of item.lessonIds) if (!lessonById[id]) throw new Error(`Missing lesson ${id}`)
    for (const id of item.prerequisiteIds) if (!moduleById[id]) throw new Error(`Missing prerequisite ${id}`)
  }
  for (const item of lessons) if (item.skillIds.length === 0 || item.explanation.length === 0) throw new Error(`Incomplete lesson ${item.id}`)
  return true
}
