import type { Exercise } from '../domain/course-types'
import { professionalExercises } from './professional-exercises'

const h = (concept: string, step: string, pseudo: string): [string, string, string] => [concept, step, pseudo]

const coreExercises: Exercise[] = [
  {
    id: 'normalize-name', title: 'Normalize a name', functionName: 'normalize_name', skillIds: ['strings', 'functions'],
    prompt: 'Return a name with outside whitespace removed, internal whitespace collapsed, and each word title-cased.',
    starterCode: 'def normalize_name(name):\n    # Your code here\n    pass',
    solution: "def normalize_name(name):\n    return ' '.join(name.split()).title()",
    tests: [
      { name: 'collapses whitespace', functionName: 'normalize_name', args: ['  daniel   de vries  '], expected: 'Daniel De Vries' },
      { name: 'normalizes uppercase', functionName: 'normalize_name', args: ['ALICE'], expected: 'Alice' },
      { name: 'handles empty text', functionName: 'normalize_name', args: ['   '], expected: '' },
    ],
    hints: h('split() without an argument already removes repeated whitespace.', 'Transform the text into words, then join those words with one space.', "words = name.split()\nreturn ' '.join(words).title()"),
  },
  {
    id: 'count-truthy', title: 'Count truthy values', functionName: 'count_truthy', skillIds: ['syntax', 'loops'],
    prompt: 'Return how many items in values are truthy according to Python.',
    starterCode: 'def count_truthy(values):\n    pass',
    solution: 'def count_truthy(values):\n    return sum(1 for value in values if value)',
    tests: [
      { name: 'mixed values', functionName: 'count_truthy', args: [[0, '', [], null, 'Python', 4]], expected: 2 },
      { name: 'all false', functionName: 'count_truthy', args: [[0, false, '', []]], expected: 0 },
      { name: 'empty list', functionName: 'count_truthy', args: [[]], expected: 0 },
    ],
    hints: h('Python conditions can test a value directly.', 'Start a counter and increase it only when if value succeeds.', 'count = 0\nfor value in values:\n    if value:\n        count += 1'),
  },
  {
    id: 'describe-number', title: 'Classify a number', functionName: 'describe_number', skillIds: ['syntax', 'functions'],
    prompt: 'Return zero, positive even, positive odd, negative even, or negative odd.',
    starterCode: 'def describe_number(number):\n    pass',
    solution: "def describe_number(number):\n    if number == 0:\n        return 'zero'\n    sign = 'positive' if number > 0 else 'negative'\n    parity = 'even' if number % 2 == 0 else 'odd'\n    return f'{sign} {parity}'",
    tests: [
      { name: 'zero', functionName: 'describe_number', args: [0], expected: 'zero' },
      { name: 'positive even', functionName: 'describe_number', args: [8], expected: 'positive even' },
      { name: 'negative odd', functionName: 'describe_number', args: [-3], expected: 'negative odd' },
    ],
    hints: h('Zero needs its own case; every other integer has a sign and parity.', 'Handle zero first, then determine sign and even/odd separately.', "if number == 0: return 'zero'\nsign = ...\nparity = ..."),
  },
  {
    id: 'inclusive-primes', title: 'Find primes inclusively', functionName: 'find_primes', skillIds: ['loops', 'functions', 'complexity'],
    prompt: 'Return every prime from start through end, including end when it is prime.',
    starterCode: 'def is_prime(number):\n    pass\n\ndef find_primes(start, end):\n    pass',
    solution: 'def is_prime(number):\n    if number < 2:\n        return False\n    divisor = 2\n    while divisor * divisor <= number:\n        if number % divisor == 0:\n            return False\n        divisor += 1\n    return True\n\ndef find_primes(start, end):\n    return [number for number in range(start, end + 1) if is_prime(number)]',
    tests: [
      { name: 'normal range', functionName: 'find_primes', args: [10, 20], expected: [11, 13, 17, 19] },
      { name: 'includes endpoint', functionName: 'find_primes', args: [20, 23], expected: [23] },
      { name: 'handles negatives', functionName: 'find_primes', args: [-5, 3], expected: [2, 3] },
    ],
    hints: h('range stops before its second argument.', 'Use end + 1 and keep primality logic in is_prime.', 'for number in range(start, end + 1):\n    if is_prime(number): ...'),
  },
  {
    id: 'top-words', title: 'Finish your diagnostic: top words', functionName: 'top_words', skillIds: ['strings', 'dictionaries', 'sorting', 'exceptions'],
    prompt: 'Count words, then return (word, count) pairs sorted by count descending and word ascending. Raise ValueError for a negative limit.',
    starterCode: "def word_frequency(text):\n    # Rebuild this without debug printing\n    pass\n\ndef top_words(text, limit=3):\n    pass",
    solution: "def word_frequency(text):\n    cleaned = ''.join(char for char in text.lower() if char.isalnum() or char.isspace())\n    counts = {}\n    for word in cleaned.split():\n        counts[word] = counts.get(word, 0) + 1\n    return counts\n\ndef top_words(text, limit=3):\n    if limit < 0:\n        raise ValueError('limit cannot be negative')\n    counts = word_frequency(text)\n    return sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]",
    tests: [
      { name: 'orders by count', functionName: 'top_words', args: ['cat dog cat bird dog cat', 2], expected: [['cat', 3], ['dog', 2]] },
      { name: 'breaks ties alphabetically', functionName: 'top_words', args: ['zebra ant zebra ant', 2], expected: [['ant', 2], ['zebra', 2]] },
      { name: 'rejects negative limit', functionName: 'top_words', args: ['hello', -1], expectedException: 'ValueError' },
    ],
    hints: h('A sorting key can return more than one value.', 'Sort items using negative count first and word second.', 'sorted(counts.items(), key=lambda item: (-item[1], item[0]))'),
  },
  {
    id: 'summarize-orders', title: 'Aggregate nested order data', functionName: 'summarize_orders', skillIds: ['dictionaries', 'nested-data', 'sorting'],
    prompt: 'Return paid revenue, unpaid revenue, alphabetic paying customers, paid revenue by customer, and the most popular product with alphabetic tie-breaking.',
    starterCode: 'def summarize_orders(orders):\n    pass',
    solution: "def summarize_orders(orders):\n    paid = unpaid = 0\n    customers = set()\n    by_customer = {}\n    products = {}\n    for order in orders:\n        products[order['product']] = products.get(order['product'], 0) + 1\n        if order['paid']:\n            paid += order['price']\n            customers.add(order['customer'])\n            by_customer[order['customer']] = by_customer.get(order['customer'], 0) + order['price']\n        else:\n            unpaid += order['price']\n    popular = min(products, key=lambda product: (-products[product], product)) if products else None\n    return {'paid_revenue': paid, 'unpaid_revenue': unpaid, 'paying_customers': sorted(customers), 'revenue_by_customer': by_customer, 'most_popular_product': popular}",
    tests: [
      { name: 'aggregates sample', functionName: 'summarize_orders', args: [[{customer:'Alice',product:'Keyboard',price:80,paid:true},{customer:'Bob',product:'Mouse',price:25,paid:false},{customer:'Alice',product:'Monitor',price:240,paid:true},{customer:'Charlie',product:'Mouse',price:25,paid:true},{customer:'Bob',product:'Keyboard',price:80,paid:true}]], expected: {paid_revenue:425,unpaid_revenue:25,paying_customers:['Alice','Bob','Charlie'],revenue_by_customer:{Alice:320,Charlie:25,Bob:80},most_popular_product:'Keyboard'} },
      { name: 'empty orders', functionName: 'summarize_orders', args: [[]], expected: {paid_revenue:0,unpaid_revenue:0,paying_customers:[],revenue_by_customer:{},most_popular_product:null} },
    ],
    hints: h('Build each result field while visiting every order once.', 'Use a set for unique customers and dictionaries for accumulated totals.', 'for order in orders:\n    products[...] = products.get(..., 0) + 1\n    if order[\'paid\']: ...'),
  },
  {
    id: 'safe-average', title: 'Average positive numbers safely', functionName: 'average_positive', skillIds: ['loops', 'exceptions', 'testing'],
    prompt: 'Return the mean of numbers strictly greater than zero. Raise ValueError when there are none.',
    starterCode: 'def average_positive(numbers):\n    pass',
    solution: "def average_positive(numbers):\n    positives = [number for number in numbers if number > 0]\n    if not positives:\n        raise ValueError('no positive numbers')\n    return sum(positives) / len(positives)",
    tests: [
      { name: 'normal input', functionName: 'average_positive', args: [[2, 4, 6]], expected: 4 },
      { name: 'ignores zero and negatives', functionName: 'average_positive', args: [[-4, 0, 2, 4]], expected: 3 },
      { name: 'raises for no positives', functionName: 'average_positive', args: [[-1, 0]], expectedException: 'ValueError' },
    ],
    hints: h('The requirement says positive, not non-negative.', 'First collect values greater than zero. Validate before dividing.', 'positives = [...]\nif not positives: raise ValueError(...)\nreturn sum(...) / len(...)'),
  },
  {
    id: 'parse-score-report', title: 'Validate a JSON score report', functionName: 'parse_score_report', skillIds: ['nested-data', 'exceptions', 'testing'],
    prompt: 'Accept a JSON string containing student records and return count, average, highest, and lowest. Raise ValueError for empty or invalid records.',
    starterCode: 'import json\n\ndef parse_score_report(text):\n    pass',
    solution: "import json\n\ndef parse_score_report(text):\n    students = json.loads(text)\n    if not students:\n        raise ValueError('empty report')\n    for student in students:\n        if not isinstance(student.get('name'), str) or not isinstance(student.get('score'), (int, float)):\n            raise ValueError('invalid student')\n    return {'student_count': len(students), 'average_score': sum(s['score'] for s in students) / len(students), 'highest': max(students, key=lambda s: s['score']), 'lowest': min(students, key=lambda s: s['score'])}",
    allowedImports: ['json'],
    tests: [
      { name: 'valid report', functionName: 'parse_score_report', args: ['[{"name":"Alice","score":84},{"name":"Bob","score":91},{"name":"Charlie","score":77}]'], expected: {student_count:3,average_score:84,highest:{name:'Bob',score:91},lowest:{name:'Charlie',score:77}} },
      { name: 'empty report', functionName: 'parse_score_report', args: ['[]'], expectedException: 'ValueError' },
      { name: 'bad score', functionName: 'parse_score_report', args: ['[{"name":"Alice","score":"high"}]'], expectedException: 'ValueError' },
    ],
    hints: h('Parsing and validating are separate responsibilities.', 'Load JSON, reject an empty list, then validate every record before calculating.', 'students = json.loads(text)\nif not students: raise ValueError(...)\nfor student in students: ...'),
  },
  {
    id: 'bank-account', title: 'Model a bank account', functionName: 'account_scenario', skillIds: ['oop', 'exceptions', 'testing'],
    prompt: 'Create BankAccount with deposit and withdraw validation, then implement account_scenario(start, deposits, withdrawals) returning final balance and transaction strings.',
    starterCode: 'class InsufficientFundsError(Exception):\n    pass\n\nclass BankAccount:\n    pass\n\ndef account_scenario(start, deposits, withdrawals):\n    pass',
    solution: "class InsufficientFundsError(Exception):\n    pass\n\nclass BankAccount:\n    def __init__(self, owner, balance=0):\n        if balance < 0: raise ValueError('negative balance')\n        self.owner = owner\n        self.balance = balance\n        self._transactions = []\n    def deposit(self, amount):\n        if amount <= 0: raise ValueError('invalid deposit')\n        self.balance += amount\n        self._transactions.append(f'deposit:{amount}')\n    def withdraw(self, amount):\n        if amount <= 0: raise ValueError('invalid withdrawal')\n        if amount > self.balance: raise InsufficientFundsError()\n        self.balance -= amount\n        self._transactions.append(f'withdraw:{amount}')\n\ndef account_scenario(start, deposits, withdrawals):\n    account = BankAccount('Learner', start)\n    for amount in deposits: account.deposit(amount)\n    for amount in withdrawals: account.withdraw(amount)\n    return {'balance': account.balance, 'transactions': account._transactions}",
    tests: [
      { name: 'normal scenario', functionName: 'account_scenario', args: [100, [50], [30]], expected: {balance:120,transactions:['deposit:50','withdraw:30']} },
      { name: 'invalid deposit', functionName: 'account_scenario', args: [100, [0], []], expectedException: 'ValueError' },
      { name: 'insufficient funds', functionName: 'account_scenario', args: [20, [], [30]], expectedException: 'InsufficientFundsError' },
    ],
    hints: h('A class keeps related state and behavior together.', 'Validate before changing balance; record a transaction only after success.', 'class BankAccount:\n    def deposit(self, amount): ...\n    def withdraw(self, amount): ...'),
  },
  {
    id: 'binary-search', title: 'Binary search', functionName: 'binary_search', skillIds: ['algorithms', 'complexity'],
    prompt: 'Return the index of target in a sorted list, or -1 when absent. Do not use list.index.',
    starterCode: 'def binary_search(values, target):\n    pass',
    solution: 'def binary_search(values, target):\n    low, high = 0, len(values) - 1\n    while low <= high:\n        middle = (low + high) // 2\n        if values[middle] == target: return middle\n        if values[middle] < target: low = middle + 1\n        else: high = middle - 1\n    return -1',
    tests: [
      { name: 'finds middle', functionName: 'binary_search', args: [[1,3,5,7,9], 5], expected: 2 },
      { name: 'finds edge', functionName: 'binary_search', args: [[1,3,5,7,9], 9], expected: 4 },
      { name: 'missing', functionName: 'binary_search', args: [[1,3,5,7,9], 4], expected: -1 },
    ],
    hints: h('Each comparison lets you discard half the remaining list.', 'Track low and high inclusive indexes and move one boundary past middle.', 'while low <= high:\n    middle = ...\n    if value < target: low = middle + 1'),
  },
  {
    id: 'valid-brackets', title: 'Validate brackets with a stack', functionName: 'valid_brackets', skillIds: ['algorithms', 'dictionaries'],
    prompt: 'Return whether (), [], and {} are correctly nested.',
    starterCode: 'def valid_brackets(text):\n    pass',
    solution: "def valid_brackets(text):\n    pairs = {')':'(', ']':'[', '}':'{'}\n    stack = []\n    for char in text:\n        if char in '([{': stack.append(char)\n        elif char in pairs:\n            if not stack or stack.pop() != pairs[char]: return False\n    return not stack",
    tests: [
      { name: 'nested', functionName: 'valid_brackets', args: ['({[]})'], expected: true },
      { name: 'wrong order', functionName: 'valid_brackets', args: ['([)]'], expected: false },
      { name: 'unfinished', functionName: 'valid_brackets', args: ['(()'], expected: false },
    ],
    hints: h('The last opening bracket must be the first one closed.', 'Push openings; for each closing bracket, pop and compare.', "pairs = {')':'(', ...}\nstack = []\nfor char in text: ..."),
  },
  {
    id: 'bfs-path', title: 'Find a route with BFS', functionName: 'bfs_path', skillIds: ['algorithms', 'nested-data', 'complexity'],
    prompt: 'Return the shortest unweighted path from start to goal in an adjacency dictionary, or an empty list.',
    starterCode: 'from collections import deque\n\ndef bfs_path(graph, start, goal):\n    pass',
    solution: "from collections import deque\n\ndef bfs_path(graph, start, goal):\n    queue = deque([[start]])\n    seen = {start}\n    while queue:\n        path = queue.popleft()\n        node = path[-1]\n        if node == goal: return path\n        for neighbor in graph.get(node, []):\n            if neighbor not in seen:\n                seen.add(neighbor)\n                queue.append(path + [neighbor])\n    return []",
    allowedImports: ['collections'],
    tests: [
      { name: 'shortest route', functionName: 'bfs_path', args: [{A:['B','C'],B:['D'],C:['D'],D:[]}, 'A', 'D'], expected: ['A','B','D'] },
      { name: 'same node', functionName: 'bfs_path', args: [{A:['B']}, 'A', 'A'], expected: ['A'] },
      { name: 'unreachable', functionName: 'bfs_path', args: [{A:['B'],B:[],C:[]}, 'A', 'C'], expected: [] },
    ],
    hints: h('BFS explores every path of length n before length n + 1.', 'Put complete paths in a queue and mark nodes when they enter it.', 'queue = deque([[start]])\nseen = {start}\nwhile queue:\n    path = queue.popleft()'),
  },
  {
    id: 'parse-api-page', title: 'Parse an API page', functionName: 'parse_api_page', skillIds: ['apis', 'nested-data', 'exceptions'],
    prompt: 'Accept an API response dictionary. Return item names and next_page. Raise ValueError unless status is 200 and data.items is a list.',
    starterCode: 'def parse_api_page(response):\n    pass',
    solution: "def parse_api_page(response):\n    if response.get('status') != 200: raise ValueError('request failed')\n    data = response.get('data')\n    if not isinstance(data, dict) or not isinstance(data.get('items'), list): raise ValueError('invalid response')\n    return {'names': [item['name'] for item in data['items']], 'next_page': data.get('next_page')}",
    tests: [
      { name: 'valid page', functionName: 'parse_api_page', args: [{status:200,data:{items:[{name:'Ajax'},{name:'PSV'}],next_page:2}}], expected: {names:['Ajax','PSV'],next_page:2} },
      { name: 'last page', functionName: 'parse_api_page', args: [{status:200,data:{items:[],next_page:null}}], expected: {names:[],next_page:null} },
      { name: 'bad status', functionName: 'parse_api_page', args: [{status:500,data:{}}], expectedException: 'ValueError' },
    ],
    hints: h('Treat external data as untrusted input.', 'Validate status, then the shape of data and items, before extracting names.', "if response.get('status') != 200: raise ValueError(...)\ndata = response.get('data')"),
  },
  {
    id: 'extract-links', title: 'Extract links from HTML', functionName: 'extract_links', skillIds: ['scraping', 'strings', 'security'],
    prompt: 'Using html.parser, return unique http/https href values in first-seen order. Ignore javascript, mailto, and duplicates.',
    starterCode: 'from html.parser import HTMLParser\n\ndef extract_links(html):\n    pass',
    solution: "from html.parser import HTMLParser\n\ndef extract_links(html):\n    links = []\n    class Parser(HTMLParser):\n        def handle_starttag(self, tag, attrs):\n            if tag != 'a': return\n            href = dict(attrs).get('href', '')\n            if href.startswith(('http://', 'https://')) and href not in links:\n                links.append(href)\n    Parser().feed(html)\n    return links",
    allowedImports: ['html'],
    tests: [
      { name: 'extracts safe links', functionName: 'extract_links', args: ['<a href="https://example.com">A</a><a href="mailto:x@y.com">M</a><a href="https://example.com">Again</a>'], expected: ['https://example.com'] },
      { name: 'supports http', functionName: 'extract_links', args: ['<a href="http://example.org/x">X</a>'], expected: ['http://example.org/x'] },
      { name: 'empty', functionName: 'extract_links', args: ['<p>No links</p>'], expected: [] },
    ],
    hints: h('HTMLParser calls handle_starttag for each opening tag.', 'For a tags, turn attrs into a dictionary and inspect href.', 'class Parser(HTMLParser):\n    def handle_starttag(self, tag, attrs): ...'),
  },
  {
    id: 'clean-records', title: 'Clean scraped records', functionName: 'clean_records', skillIds: ['scraping', 'data-analysis', 'exceptions'],
    prompt: 'Normalize team names, parse integer scores, drop duplicate (team, score) records, and skip invalid rows.',
    starterCode: 'def clean_records(records):\n    pass',
    solution: "def clean_records(records):\n    cleaned, seen = [], set()\n    for record in records:\n        try:\n            team = ' '.join(record['team'].split()).title()\n            score = int(record['score'])\n        except (KeyError, TypeError, ValueError):\n            continue\n        key = (team, score)\n        if team and key not in seen:\n            seen.add(key)\n            cleaned.append({'team': team, 'score': score})\n    return cleaned",
    tests: [
      { name: 'cleans and deduplicates', functionName: 'clean_records', args: [[{team:' ajax ',score:'3'},{team:'AJAX',score:3},{team:' psv',score:'x'},{score:2}]], expected: [{team:'Ajax',score:3}] },
      { name: 'keeps order', functionName: 'clean_records', args: [[{team:'psv',score:'2'},{team:'ajax',score:'1'}]], expected: [{team:'Psv',score:2},{team:'Ajax',score:1}] },
    ],
    hints: h('Cleaning pipelines often skip records that cannot satisfy the data contract.', 'Use try/except around field access and int conversion; use a set for duplicate keys.', 'cleaned, seen = [], set()\nfor record in records:\n    try: ...\n    except (...): continue'),
  },
  {
    id: 'moving-average', title: 'Calculate a moving average', functionName: 'moving_average', skillIds: ['data-analysis', 'statistics', 'loops'],
    prompt: 'Return the average of each consecutive window. Raise ValueError when window is non-positive or larger than the data.',
    starterCode: 'def moving_average(values, window):\n    pass',
    solution: "def moving_average(values, window):\n    if window <= 0 or window > len(values): raise ValueError('invalid window')\n    return [sum(values[i:i+window]) / window for i in range(len(values) - window + 1)]",
    tests: [
      { name: 'window three', functionName: 'moving_average', args: [[1,2,3,4,5], 3], expected: [2,3,4] },
      { name: 'window one', functionName: 'moving_average', args: [[2,4], 1], expected: [2,4] },
      { name: 'invalid window', functionName: 'moving_average', args: [[1,2], 3], expectedException: 'ValueError' },
    ],
    hints: h('A window of size w has len(values) - w + 1 valid starting positions.', 'Slice each window, sum it, and divide by window.', 'for i in range(len(values) - window + 1):\n    result.append(sum(values[i:i+window]) / window)'),
  },
  {
    id: 'standardize', title: 'Standardize values', functionName: 'standardize', skillIds: ['statistics', 'data-analysis'],
    prompt: 'Return z-scores using population standard deviation. Raise ValueError for empty input or zero spread.',
    starterCode: 'def standardize(values):\n    pass',
    solution: "def standardize(values):\n    if not values: raise ValueError('empty values')\n    mean = sum(values) / len(values)\n    variance = sum((value - mean) ** 2 for value in values) / len(values)\n    if variance == 0: raise ValueError('zero spread')\n    std = variance ** 0.5\n    return [(value - mean) / std for value in values]",
    tests: [
      { name: 'symmetric values', functionName: 'standardize', args: [[1,2,3]], expected: [-1.2247448714,0,1.2247448714], comparison: 'numeric-tolerance', tolerance: 1e-6 },
      { name: 'constant values', functionName: 'standardize', args: [[4,4,4]], expectedException: 'ValueError' },
      { name: 'empty', functionName: 'standardize', args: [[]], expectedException: 'ValueError' },
    ],
    hints: h('A z-score measures distance from the mean in standard deviations.', 'Compute mean, population variance, its square root, then transform each value.', 'mean = ...\nvariance = sum((x - mean) ** 2 ...) / len(values)\nstd = variance ** 0.5'),
  },
  {
    id: 'chronological-split', title: 'Split time-ordered data', functionName: 'chronological_split', skillIds: ['machine-learning', 'data-analysis'],
    prompt: 'Split records into train and test without shuffling. test_fraction must be greater than 0 and less than 1; test gets at least one record.',
    starterCode: 'def chronological_split(records, test_fraction):\n    pass',
    solution: "def chronological_split(records, test_fraction):\n    if not 0 < test_fraction < 1 or len(records) < 2: raise ValueError('invalid split')\n    test_size = max(1, int(len(records) * test_fraction))\n    split = len(records) - test_size\n    return records[:split], records[split:]",
    tests: [
      { name: 'keeps chronology', functionName: 'chronological_split', args: [[1,2,3,4,5], 0.4], expected: [[1,2,3],[4,5]] },
      { name: 'at least one test row', functionName: 'chronological_split', args: [[1,2,3], 0.1], expected: [[1,2],[3]] },
      { name: 'invalid fraction', functionName: 'chronological_split', args: [[1,2,3], 1], expectedException: 'ValueError' },
    ],
    hints: h('Sports predictions must not train on future matches.', 'Calculate test size, then slice once without shuffling.', 'test_size = max(1, int(len(records) * test_fraction))\nsplit = len(records) - test_size'),
  },
  {
    id: 'classification-metrics', title: 'Classification metrics', functionName: 'classification_metrics', skillIds: ['machine-learning', 'statistics', 'dictionaries'],
    prompt: 'For binary labels, return accuracy, precision, recall, tp, tn, fp, and fn. Use 0 when a precision or recall denominator is zero.',
    starterCode: 'def classification_metrics(actual, predicted):\n    pass',
    solution: "def classification_metrics(actual, predicted):\n    if len(actual) != len(predicted) or not actual: raise ValueError('invalid labels')\n    tp = sum(a == 1 and p == 1 for a,p in zip(actual,predicted))\n    tn = sum(a == 0 and p == 0 for a,p in zip(actual,predicted))\n    fp = sum(a == 0 and p == 1 for a,p in zip(actual,predicted))\n    fn = sum(a == 1 and p == 0 for a,p in zip(actual,predicted))\n    return {'accuracy': (tp+tn)/len(actual), 'precision': tp/(tp+fp) if tp+fp else 0, 'recall': tp/(tp+fn) if tp+fn else 0, 'tp':tp, 'tn':tn, 'fp':fp, 'fn':fn}",
    tests: [
      { name: 'mixed predictions', functionName: 'classification_metrics', args: [[1,1,0,0],[1,0,1,0]], expected: {accuracy:0.5,precision:0.5,recall:0.5,tp:1,tn:1,fp:1,fn:1} },
      { name: 'no positive predictions', functionName: 'classification_metrics', args: [[1,0],[0,0]], expected: {accuracy:0.5,precision:0,recall:0,tp:0,tn:1,fp:0,fn:1} },
      { name: 'invalid sizes', functionName: 'classification_metrics', args: [[1],[1,0]], expectedException: 'ValueError' },
    ],
    hints: h('Start by counting the four cells of the confusion matrix.', 'Use zip(actual, predicted), then calculate each metric from tp/tn/fp/fn.', 'tp = sum(a == 1 and p == 1 for a, p in zip(...))'),
  },
  {
    id: 'majority-baseline', title: 'Build a majority baseline', functionName: 'majority_baseline', skillIds: ['machine-learning', 'statistics'],
    prompt: 'Return predictions for test_size using the most common training label. Resolve ties by choosing the smaller label.',
    starterCode: 'def majority_baseline(train_labels, test_size):\n    pass',
    solution: "def majority_baseline(train_labels, test_size):\n    if not train_labels or test_size < 0: raise ValueError('invalid input')\n    counts = {}\n    for label in train_labels: counts[label] = counts.get(label, 0) + 1\n    winner = min(counts, key=lambda label: (-counts[label], label))\n    return [winner] * test_size",
    tests: [
      { name: 'majority one', functionName: 'majority_baseline', args: [[1,1,0], 3], expected: [1,1,1] },
      { name: 'tie chooses smaller', functionName: 'majority_baseline', args: [[1,0], 2], expected: [0,0] },
      { name: 'empty labels', functionName: 'majority_baseline', args: [[], 2], expectedException: 'ValueError' },
    ],
    hints: h('A model is useful only if it beats a simple reference strategy.', 'Count labels and rank by negative count, then label.', 'winner = min(counts, key=lambda label: (-counts[label], label))'),
  },
  {
    id: 'dot-product', title: 'Compute a dot product', functionName: 'dot', skillIds: ['linear-algebra', 'neural-networks', 'loops'],
    prompt: 'Return the dot product of equally sized vectors. Raise ValueError for different lengths or empty vectors.',
    starterCode: 'def dot(a, b):\n    pass',
    solution: "def dot(a, b):\n    if not a or len(a) != len(b): raise ValueError('vectors must match')\n    return sum(x * y for x, y in zip(a, b))",
    tests: [
      { name: 'basic vectors', functionName: 'dot', args: [[1,2,3],[4,5,6]], expected: 32 },
      { name: 'negative values', functionName: 'dot', args: [[1,-1],[3,4]], expected: -1 },
      { name: 'mismatched vectors', functionName: 'dot', args: [[1],[1,2]], expectedException: 'ValueError' },
    ],
    hints: h('A dot product is the sum of pairwise products.', 'Pair values with zip, multiply each pair, then sum.', 'return sum(x * y for x, y in zip(a, b))'),
  },
  {
    id: 'gradient-step', title: 'Take a gradient-descent step', functionName: 'gradient_step', skillIds: ['linear-algebra', 'neural-networks'],
    prompt: 'Return updated parameters where each parameter moves opposite its gradient by learning_rate.',
    starterCode: 'def gradient_step(parameters, gradients, learning_rate):\n    pass',
    solution: "def gradient_step(parameters, gradients, learning_rate):\n    if len(parameters) != len(gradients) or learning_rate <= 0: raise ValueError('invalid step')\n    return [parameter - learning_rate * gradient for parameter, gradient in zip(parameters, gradients)]",
    tests: [
      { name: 'moves downhill', functionName: 'gradient_step', args: [[1,2],[0.5,-1],0.1], expected: [0.95,2.1], comparison: 'numeric-tolerance', tolerance: 1e-9 },
      { name: 'zero gradient', functionName: 'gradient_step', args: [[3],[0],0.2], expected: [3] },
      { name: 'invalid rate', functionName: 'gradient_step', args: [[1],[1],0], expectedException: 'ValueError' },
    ],
    hints: h('The gradient points uphill, so learning moves in the opposite direction.', 'Update each parameter with parameter - learning_rate * gradient.', 'updated = p - learning_rate * g'),
  },
  {
    id: 'dense-neuron', title: 'Run a dense neuron', functionName: 'neuron', skillIds: ['linear-algebra', 'neural-networks'],
    prompt: 'Compute weighted sum plus bias and apply ReLU: max(0, value).',
    starterCode: 'def neuron(inputs, weights, bias):\n    pass',
    solution: "def neuron(inputs, weights, bias):\n    if len(inputs) != len(weights): raise ValueError('shape mismatch')\n    value = sum(x * w for x, w in zip(inputs, weights)) + bias\n    return max(0, value)",
    tests: [
      { name: 'positive activation', functionName: 'neuron', args: [[1,2],[0.5,1],-1], expected: 1.5 },
      { name: 'relu clamps negative', functionName: 'neuron', args: [[1],[1],-2], expected: 0 },
      { name: 'shape mismatch', functionName: 'neuron', args: [[1,2],[1],0], expectedException: 'ValueError' },
    ],
    hints: h('A dense neuron is a dot product, a bias, and an activation.', 'Compute the weighted sum first; then return the larger of zero and that value.', 'value = sum(x*w for ...) + bias\nreturn max(0, value)'),
  },
  {
    id: 'recommend-items', title: 'Rank recommendations', functionName: 'recommend', skillIds: ['algorithms', 'machine-learning', 'sorting'],
    prompt: 'Given item score dictionaries, exclude seen IDs and return up to limit IDs sorted by score descending then ID ascending.',
    starterCode: 'def recommend(items, seen_ids, limit=3):\n    pass',
    solution: "def recommend(items, seen_ids, limit=3):\n    if limit < 0: raise ValueError('negative limit')\n    candidates = [item for item in items if item['id'] not in set(seen_ids)]\n    candidates.sort(key=lambda item: (-item['score'], item['id']))\n    return [item['id'] for item in candidates[:limit]]",
    tests: [
      { name: 'filters and ranks', functionName: 'recommend', args: [[{id:'b',score:0.8},{id:'a',score:0.8},{id:'c',score:0.9}], ['c'], 2], expected: ['a','b'] },
      { name: 'limit zero', functionName: 'recommend', args: [[{id:'a',score:1}], [], 0], expected: [] },
      { name: 'negative limit', functionName: 'recommend', args: [[], [], -1], expectedException: 'ValueError' },
    ],
    hints: h('Recommendation ranking is filtering followed by deterministic sorting.', 'Remove seen items, sort on (-score, id), then slice.', "candidates.sort(key=lambda item: (-item['score'], item['id']))"),
  },
  {
    id: 'flappy-fitness', title: 'Design Flappy Bird fitness', functionName: 'flappy_fitness', skillIds: ['machine-learning', 'algorithms'],
    prompt: 'Return survival_frames + 100 * pipes_passed - 0.5 * distance_from_gap. Clamp the result at zero.',
    starterCode: 'def flappy_fitness(survival_frames, pipes_passed, distance_from_gap):\n    pass',
    solution: 'def flappy_fitness(survival_frames, pipes_passed, distance_from_gap):\n    if min(survival_frames, pipes_passed, distance_from_gap) < 0: raise ValueError("values cannot be negative")\n    return max(0, survival_frames + 100 * pipes_passed - 0.5 * distance_from_gap)',
    tests: [
      { name: 'rewards progress', functionName: 'flappy_fitness', args: [300,2,20], expected: 490 },
      { name: 'clamps zero', functionName: 'flappy_fitness', args: [5,0,20], expected: 0 },
      { name: 'rejects negative values', functionName: 'flappy_fitness', args: [-1,0,0], expectedException: 'ValueError' },
    ],
    hints: h('Fitness converts several goals into one score.', 'Calculate each reward/penalty term, add them, then clamp.', 'score = survival_frames + 100 * pipes_passed - 0.5 * distance_from_gap\nreturn max(0, score)'),
  },
]

export const exercises: Exercise[] = [...coreExercises, ...professionalExercises]
export const exerciseById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]))
