import { test } from '@playwright/test'

test('captures the presentation surfaces', async ({ page }, testInfo) => {
  const suffix = testInfo.project.name
  await page.goto('/#/overview')
  await page.locator('.nav-item.is-active').waitFor({ state: 'attached' })
  await page.waitForTimeout(250)
  await page.mouse.move(1000, 500)
  await page.screenshot({ path: `screenshots/overview-${suffix}.png`, fullPage: true })
  await page.goto('/#/analytics')
  await page.locator('.nav-item.is-active').waitFor({ state: 'attached' })
  await page.waitForTimeout(250)
  await page.mouse.move(1000, 500)
  await page.screenshot({ path: `screenshots/analytics-${suffix}.png`, fullPage: true })
  await page.goto('/#/crm')
  await page.locator('.nav-item.is-active').waitFor({ state: 'attached' })
  await page.waitForTimeout(250)
  await page.mouse.move(1000, 500)
  await page.screenshot({ path: `screenshots/crm-${suffix}.png`, fullPage: true })
  await page.goto('/#/integrations')
  await page.locator('.nav-item.is-active').waitFor({ state: 'attached' })
  await page.waitForTimeout(250)
  await page.mouse.move(1000, 500)
  await page.screenshot({ path: `screenshots/integrations-${suffix}.png`, fullPage: true })
})
